### ISSUE TITLE
[Support] Keyword mismatch

### ISSUE THREAD

**Issue by yqlbu** [daeuniverse/dae#104]
## What would you like us to support (In short summary)

Seems like the `keyword` matching does NOT actually take effect. Consider the following configs:

```python
    domain(suffix:linkedin.com) -> proxy
    domain(keyword:linkedin) -> proxy
    domain(keyword:linuxfoundation,
           keyword:notion,
           keyword:github,
           keyword:gist,
           keyword:aws,
           keyword:oracle,
           keyword:quay,
           keyword:docker,
           keyword:kubernetes,
           keyword:yahoo,
           keyword:pikpak
    ) -> proxy
```

**Comment by youwei5683** [comment]
版本: dae version 0.1.8 测试keyword可以工作
routing {
	pname(NetworkManager, systemd-resolved, dnsmasq, AdGuardHome) -> must_direct
	dip(224.0.0.0/3) -> direct	

    l4proto(udp) && dport(443) && domain(geosite:youtube) -> block
	
	domain(keyword: kakao) -> Crastar

    #chatGPT
    domain(openai.com,
           pay.openai.com,
           chat.openai.com,
           challenges.cloudflare.com,
           auth0.openai.com,
           platform.openai.com,
           # Add ai.com
           ai.com,
           # Add stripe.com
           invoice.stripe.com,
           stripe.com,
           # Add justmysocks.ne
           justmysocks.ne) -> must_chatgpt
	
	#直连
	dip(geoip:private, geoip:cn) -> must_direct
	domain(geosite:cn) -> must_direct
	
	### 以下为自定义规则
	
	dport(23-65535) -> proxy
	fallback: proxy
}
