### ISSUE TITLE
[Support] Add version control on config.dae

### ISSUE THREAD

**Issue by yqlbu** [daeuniverse/dae#105]
## What would you like us to support (In short summary)

In future release cycles, we should consider adding a link to point users to the `example.dae` based on the associated release tag. Consider the following release notes:

**Full Changelog**: <https://github.com/daeuniverse/dae/compare/v0.1.10rc...v0.1.10rc1>

**Example Config**: <https://github.com/daeuniverse/dae/blob/v0.1.10rc1/example.dae>

## What's next

We should also make some modifications to the `installer` script, including logic to pull the latest `example.dae` for any new future releases.

**Comment by yqlbu** [comment]
Also, link to #103

**Comment by yqlbu** [comment]
Installer fix is linked to https://github.com/daeuniverse/dae-installer/commit/5166ea8c15c941bd32968c2de2c266d9766d7f9c

**Comment by mzz2017** [comment]
I don't think we should add version related files in `main` branch. It should be controlled using `git` in different tags. It is natural supported.

**Comment by yqlbu** [comment]
> I don't think we should add version related files in `main` branch. It should be controlled using `git` in different tags. It is natural supported.

Yes, I agree. I think all we need is to add the following to future releases:

> **Full Changelog**: <https://github.com/daeuniverse/dae/compare/v0.1.10rc...v0.1.10rc1>
> **Example Config**: <https://github.com/daeuniverse/dae/blob/v0.1.10rc1/example.dae>

**Comment by mzz2017** [comment]
> Yes, I agree. I think all we need is to add the following to future releases:

I got it. It is a good idea.
