### ISSUE TITLE
怎么用，看不懂

### ISSUE THREAD

**Issue by newyorkthink** [daeuniverse/dae#114]
## Environment

- Dae version (use `dae --version`):
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mzz2017** [comment]
https://github.com/daeuniverse/dae/blob/main/docs/getting-started/README_zh.md

**Comment by mzz2017** [comment]
问题指向性不强，我先把 issue 锁了。
