### ISSUE TITLE
加油，各位大佬大，xanmond ，能不能用上dae，看各位的了，飞龙在天，喵喵 :)

### ISSUE THREAD

**Issue by newyorkthink** [daeuniverse/dae#127]
[[[https://xanmod.org/_detail/xanmod_wallpaper.png?id=download](url)](https://xanmod.org/_detail/xanmod_wallpaper.png?id=download)](https://xanmod.org/_detail/xanmod_wallpaper.png?id=download)

**Comment by kunish** [comment]
感谢老铁提出的宝贵建议，喵喵 ;)

**Comment by newyorkthink** [comment]
https://github.com/daeuniverse/dae/issues/121

**Comment by wanlce** [comment]
> #121

支持 dae 的 xanmod 内核配置, 自己编译下叭   
https://gist.github.com/wanlce/ff7cbc9bc6145219c222a02ddda9b11d

**Comment by Yuyuko-sama** [comment]
> > #121
> 
> 支持 dae 的 xanmod 内核配置, 自己编译下叭 https://gist.github.com/wanlce/ff7cbc9bc6145219c222a02ddda9b11d

大佬，为啥我编译的时候其他参数都编译上了，唯独：

**Comment by wanlce** [comment]
@Yuyuko-sama 它是有一些前置依赖的
![image](https://github.com/daeuniverse/dae/assets/55907021/2d24021d-591d-497c-b175-4a26a1ab48b6)
话说 xanmod 的主线内核这两个配置已经默认是 y 了哎
https://github.com/xanmod/linux/blob/b10e545792f07fd8245dffc013b45440a8dbc607/CONFIGS/xanmod/gcc/config_x86-64-v4#L11686

现在只需要改就好了
```
CONFIG_DEBUG_INFO_REDUCED=n
CONFIG_KPROBE_EVENTS=y
CONFIG_FTRACE=y
CONFIG_NET_CLS_BPF=y
CONFIG_BPF_EVENTS=y
```

**Comment by Yuyuko-sama** [comment]
> @Yuyuko-sama 它是有一些前置依赖的 ![image](https://user-images.githubusercontent.com/55907021/270539562-2d24021d-591d-497c-b175-4a26a1ab48b6.png) 话说 xanmod 的主线内核这两个配置已经默认是 y 了哎 https://github.com/xanmod/linux/blob/b10e545792f07fd8245dffc013b45440a8dbc607/CONFIGS/xanmod/gcc/config_x86-64-v4#L11686
> 
> 现在只需要改就好了
> 
> ```
> CONFIG_DEBUG_INFO_REDUCED=n
> CONFIG_KPROBE_EVENTS=y
> CONFIG_FTRACE=y
> CONFIG_NET_CLS_BPF=y
> CONFIG_BPF_EVENTS=y
> ```

谢谢大佬，才发现xanmod 要V4才 y，V3里头好像没看到勾选。  主要是不确定我E5-2618L V4 支不支持V4 emmmm

**Comment by wanlce** [comment]
> 谢谢大佬，才发现xanmod 要V4才 y，V3里头好像没看到勾选。 主要是不确定我E5-2618L V4 支不支持V4 emmmm

https://github.com/xanmod/linux/blob/b10e545792f07fd8245dffc013b45440a8dbc607/CONFIGS/xanmod/gcc/config_x86-64-v3#L11686
xanmod 的 v1-v4 这个配置都一样的

支持不支持v4 不影响，前面提到的内核选项开了就可以润大鹅
想看架构可以执行  `/lib/ld-linux-x86-64.so.2 --help | grep supported`  看看

**Comment by Yuyuko-sama** [comment]
顺带贴一个make menuconfig 的菜单路径指引给其他人方便：


Reduce debugging information
modulename: debug_info.ko
configname: CONFIG_DEBUG_INFO_REDUCED
Linux Kernel Configuration
└─> Kernel hacking
└─> Compile-time checks and compiler options
└─> Reduce debugging information

modulename: trace_kprobe_selftest.ko and/or trace_kprobe.ko
configname: CONFIG_KPROBE_EVENTS
Linux Kernel Configuration
└─> Kernel hacking
└─> Tracers
└─> Enable kprobes-based dynamic events

configname: CONFIG_FTRACE
Linux Kernel Configuration
└─> Kernel hacking
└─> Tracers

BPF-based classifier
modulename: cls_bpf.ko
configname: CONFIG_NET_CLS_BPF
Linux Kernel Configuration
└─> Networking support
└─> Networking options
└─> QoS and/or fair queueing
└─> BPF-based classifier

CONFIG_BPF_EVENTS (not configurable)
modulename: bpf_trace.ko
configname: CONFIG_BPF_EVENTS
Linux Kernel Configuration
└─> Kernel hacking
└─> Tracers
└─> BPF_EVENTS

**Comment by Yuyuko-sama** [comment]
> > @Yuyuko-sama 它是有一些前置依赖的 ![image](https://user-images.githubusercontent.com/55907021/270539562-2d24021d-591d-497c-b175-4a26a1ab48b6.png) 话说 xanmod 的主线内核这两个配置已经默认是 y 了哎 https://github.com/xanmod/linux/blob/b10e545792f07fd8245dffc013b45440a8dbc607/CONFIGS/xanmod/gcc/config_x86-64-v4#L11686
> > 现在只需要改就好了
> > ```
> > CONFIG_DEBUG_INFO_REDUCED=n
> > CONFIG_KPROBE_EVENTS=y
> > CONFIG_FTRACE=y
> > CONFIG_NET_CLS_BPF=y
> > CONFIG_BPF_EVENTS=y
> > ```
> 
> 谢谢大佬，才发现xanmod 要V4才 y，V3里头好像没看到勾选。 主要是不确定我E5-2618L V4 支不支持V4 emmmm

![image](https://github.com/daeuniverse/dae/assets/40657629/3bff96ad-6286-4e60-bb86-19540c1afb4f)
不知道为啥，我编译的时候.config 里头看了有他俩：
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
结果编译完的boot/config里头别的都有，他俩又不见了= =

**Comment by Yuyuko-sama** [comment]
编译成功了，谢谢大佬。这里头是编译好的6.5.5 xanmod内核文件，以及编译方法。
https://drive.google.com/drive/folders/1HRXJKYijv40HCmLDkcnUJt1asBi_Rsr0?usp=sharing

**Comment by xz-dev** [comment]
> > > #121
> > 
> > 
> > 支持 dae 的 xanmod 内核配置, 自己编译下叭 https://gist.github.com/wanlce/ff7cbc9bc6145219c222a02ddda9b11d
> 
> 大佬，为啥我编译的时候其他参数都编译上了，唯独： CONFIG_DEBUG_INFO=y CONFIG_DEBUG_INFO_BTF=y 这两条写进.config编译，编译后更新内核，我看/boot/config 依然是缺失的。

有可能没安装 pahole 工具，或者 panhole 版本号低于 121，你应该用配置页面而不是直接改 .config
