### ISSUE TITLE
[Support Request] build related: dae refused to build on `mips` after `sqlite3` library change

### ISSUE THREAD

**Issue by kunish** [daeuniverse/dae#139]
## What would you like us to support (In short summary)

Check the daed project build step logs for details

https://github.com/daeuniverse/daed/actions/runs/5230019229/jobs/9443351141

**Comment by mzz2017** [comment]
Do you want to file the issue to dae-wing? Here is dae.

**Comment by mzz2017** [comment]
By the way, this problem is that the sqlite library does not support such CPU architectures.

**Comment by kunish** [comment]
> Do you want to file the issue to dae-wing? Here is dae.

Oh, sure, my bad, dont know what i was thinking

**Comment by kunish** [comment]
New issue opened [here](https://github.com/daeuniverse/dae/issues/139)
