### ISSUE TITLE
[Bug Report] FATA[0000] dae.Run: rlimit.RemoveMemlock:failed to set memlock rlimit: operation not permitted

### ISSUE THREAD

**Issue by kunish** [daeuniverse/dae#142]
## What happened

<img width="765" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/d9429bac-82d8-4e84-b1b7-19d02280aa20">

Failed to start with error

`FATA[0000] dae.Run: rlimit.RemoveMemlock:failed to set memlock rlimit: operation not permitted`

## What you expected to happen

Runs without panicking

## How to reproduce it (as minimally and precisely as possible):

Clone `daed` repo and checkout to `ci-publish-docker-image` branch

```bash
git clone git@github.com:daeuniverse/daed.git -b ci-publish-docker-image
```

Docker build and run

```bash
docker build . -t daed
docker run -it --rm daed
```

## Anything else we need to know

Origin issue opened in `dae-wing` [here](https://github.com/daeuniverse/dae-wing/issues/23)

## Environment

- Dae version (use `dae --version`):

<img width="584" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/ec022ca3-7d0f-4716-8cba-26f951240b71">

<img width="699" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/06e1b18a-2a52-4d13-a5e1-e7673a015869">

- OS (e.g `cat /etc/os-release`):

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
IMAGE_ID=archlinux
IMAGE_VERSION=2023.06.01

- Kernel (e.g. `uname -a`):

Linux dae-test 6.3.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000 x86_64 GNU/Linux

- Others:

Docker Version:

<img width="527" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/076fc891-9535-4afc-a48c-b9f14765d3e9">

**Comment by mzz2017** [comment]
@kunish https://hub.docker.com/r/daeuniverse/dae

**Comment by mzz2017** [comment]
@kunish See usage section.

**Comment by kunish** [comment]
My bad, by appending some arguments to run command, it runs

Here is the working docker run command if anyone is interested

```bash
docker run -it --rm --pid host --privileged -v /sys:/sys -p 2023:2023 daed
```

**Comment by mzz2017** [comment]
One more thing. LXC does not support, either.

**Comment by kunish** [comment]
<img width="929" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/cc55552d-d796-4cb6-addd-45189458ccd7">

No luck even with /sys mounted inside a privileged lxc container

**Comment by mzz2017** [comment]
@kunish mount bpffs and try again?

**Comment by kunish** [comment]
> @kunish mount bpffs on host and try again?
> 
> sudo mount -n -t bpf bpffs /sys/fs/bpf

It works, i guess?

<img width="1134" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/9352c2e6-ab6d-44a3-b8be-f76506e6c981">

**Comment by kunish** [comment]
Host system

<img width="498" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/cc0f4192-a481-42a5-a88b-281127309960">

Container

<img width="323" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/fb11416f-7e8f-445a-9b91-d96b77b72013">

**Comment by kunish** [comment]
<img width="601" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/b988fde6-8f53-48c7-8d97-f0fbdf4b4560">

<img width="483" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/cd0262ed-cda0-446a-9f44-55ffe637f99c">

<img width="1230" alt="image" src="https://github.com/daeuniverse/dae/assets/17328586/b4717b40-bcb0-4ca9-b278-57f0bddb1480">

**Comment by mzz2017** [comment]
Seems not good.

**Comment by kunish** [comment]
But not so bad either. At lease we found something interesting as a starting point.
