### ISSUE TITLE
unexpected field: network: kcp

### ISSUE THREAD

**Issue by newyorkthink** [daeuniverse/dae#187]
![image](https://github.com/daeuniverse/dae/assets/87791643/2c905d04-a35b-4f4c-bfc1-f9dc62d8fdba)

本人加了vmess,但是网络
![image](https://github.com/daeuniverse/dae/assets/87791643/8f10f99b-441f-4a14-a12e-12fe032c18b7)

**Comment by mzz2017** [comment]
@newyorkthink 是的，说实话 kcp 这个协议已经有些 old school 了，建议使用 tuic 作为替代。

今晚会发布 0.2.1rc1，它将支持 tuic v5，这是一个非常棒的 kcp 的平替，近期的报告反映比 hysteria 更加优秀。

**Comment by newyorkthink** [comment]
> @newyorkthink 是的，dae 不支持 kcp。说实话 kcp 这个协议已经有些 old school 了，建议使用 [tuic](https://github.com/EAimTY/tuic) 作为替代。
> 
> 今晚会发布 0.2.1rc1，dae 在这个版本将支持 tuic v5，这是一个非常棒的 kcp 的平替，近期的报告反映比 hysteria 更加优秀。

如果可以能不能支持下kcp, 毕竟我这边服务端不好改，球球大佬

**Comment by mzz2017** [comment]
目前 clash 和 clash.meta 也未支持 kcp，dae 也暂时没有这个计划。

**Comment by newyorkthink** [comment]
啥都不行，，内核不支持，换了内核，协议也不支持，算了，不用了，
没啥意义，也没啥意思

**Comment by newyorkthink** [comment]
关了，再也不关注这个项目

**Comment by MarksonHon** [comment]
好走不送
