### ISSUE TITLE
Specify a nameserver for proxy server domain

### ISSUE THREAD

**Issue by Testeera** [daeuniverse/dae#246]
## What feature you would like us to integrate into the dae project
request {
  proxy-server-nameserver: example.com
}
## Why is this needed
Proxy nodes' domain may be polluted.

**Comment by mzz2017** [comment]
This chicken-and-egg problem is hard to solve

**Comment by Testeera** [comment]
> This chicken-and-egg problem is hard to solve

Set a domestic private nameserver.

**Comment by mzz2017** [comment]
@Testeera You can define it in /etc/resolv.conf
