### ISSUE TITLE
性能疑问

### ISSUE THREAD

**Issue by shanghaojia-1** [daeuniverse/dae#268]
在工作原理文档中有提到dae与其他代理软件的区别是，其他代理软件是将流量导入到代理程序来进行分流，而dae不需要，这让dae的性能领先于其他代理软件。
根据我了解到的，openwrt上的passwall插件应该是通过ipset来设置让iptables来进行分流，而不是将所有流量均导入到代理程序，想知道这种方式和dae相比，性能会有多大差距。谢谢！

**Comment by mzz2017** [comment]
@shanghaojia-1 1，ipset 无法根据域名分流。
2，ipset 的白名单永远在自定义规则之前。
3，ipset 不方便调整。
4，性能方面感兴趣的可以自测。

**Comment by yqlbu** [comment]
Close as complete
