### ISSUE TITLE
[Support Request] 偶尔无法科学上网

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#290]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

请问这是节点的问题吗
```
time="Aug 19 11:22:24" level=debug msg="Rewrite dial target to domain" from="104.16.210.12:443" to="www.speedtest.net:443"
time="Aug 19 11:22:24" level=warning msg="handleConn: failed to dial 104.16.210.12:443: failed to select dialer from group proxy (tcp6): no alive dialer"
```

### Current Behavior

无法科学上网

### Expected Behavior

可以科学上网

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
@Karmylr juicity?

**Comment by Karmylr** [comment]
> @Karmylr juicity?

trojan

**Comment by mzz2017** [comment]
@Karmylr 节点在测联通性失败时是会被禁用一段时间的

**Comment by Karmylr** [comment]
哦

**Comment by Karmylr** [comment]
@mzz2017 连通性检查似乎不准确，节点可以使用但是还是报warning`failed to select dialer from group proxy (tcp6): no alive dialer`
![image](https://github.com/daeuniverse/dae/assets/69903376/e1f8b05b-ec23-4111-95b1-0b9badfd1afc)

**Comment by Karmylr** [comment]
而且家里的宽带没有IPv6，但是却显示了tcp6

**Comment by mzz2017** [comment]
正常

**Comment by Karmylr** [comment]
那节点在其他软件可以使用，dae还是报`failed to select dialer from group proxy (tcp6): no alive dialer`并无法使用怎么办

**Comment by mzz2017** [comment]
打开 allow_insecure 试试

**Comment by Karmylr** [comment]
daed好像没有这个开关

**Comment by Karmylr** [comment]
![image](https://github.com/daeuniverse/dae/assets/69903376/2e1ec177-294b-462a-9b97-286548b1db1c)
kanlex看了下，订阅链接导入到v2rayA后这个默认开启

**Comment by Karmylr** [comment]
正常了 谢谢

**Comment by Karmylr** [comment]
节点确实需要跳过tls证书验证，但是打开daed上的允许不安全还是会报`failed to select dialer from group proxy (tcp6): no alive dialer`

**Comment by mzz2017** [comment]
@Karmylr 那能用吗

**Comment by Karmylr** [comment]
刚启动时可以科学 过一段时间除了电报 其他国外网站无法访问 我再观察观察吧

**Comment by mzz2017** [comment]
@Karmylr 那你可以检查一下是不是 check url 的问题

**Comment by Karmylr** [comment]
![image](https://github.com/daeuniverse/dae/assets/69903376/faf7300c-2c42-470d-a815-a012940f2465)
目前是这样的，要改吗

**Comment by Karmylr** [comment]
顺便问一下，为什么要设计成节点连通性失败就禁用一段时间呢，为了自动故障转移吗

**Comment by mzz2017** [comment]
@Karmylr 只有电报能用说明是 dns 出问题了，你可以把 dns 那边的 googledns 改成 tcp:// 开头

**Comment by yqlbu** [comment]
@mzz2017 好提議

**Comment by Karmylr** [comment]
@mzz2017 全部使用国内的dns服务器，能正常解析出google等国外网站的ip，但是还是会在开启dae一段时间后无法科学

**Comment by mzz2017** [comment]
奇怪，那为什么tg是可以的

**Comment by Karmylr** [comment]
tg再过一段时间也断网了

**Comment by mzz2017** [comment]
@Karmylr 开 debug 日志，看一下 connectivity check

**Comment by Karmylr** [comment]
@mzz2017 `time="Sep 01 11:19:39" level=debug msg="Connectivity Check Failed" err="[Tls]: dial to south.steamdownload.top:11002: dial tcp: lookup south.steamdownload.top on [::1]:53: read udp [::1]:40327->[::1]:53: i/o timeout" network="tcp4(DNS)" node="2.香港 02"`

**Comment by mzz2017** [comment]
@Karmylr 你是不是在用 dnsmasq，把dnsmasq里的劫持关了

**Comment by Karmylr** [comment]
@mzz2017 在用ImmortalWrt，怎么关劫持呢

**Comment by yqlbu** [comment]
@Karmylr 那默認會有dnsmasq

**Comment by mzz2017** [comment]
@Karmylr 我不知道怎么关劫持，要么把 dnsmasq 监听端口设0，要么把dnsmasq的劫持关掉

**Comment by yqlbu** [comment]
@Karmylr 參考 https://github.com/daeuniverse/dae/issues/79

**Comment by mzz2017** [comment]
@Karmylr https://github.com/daeuniverse/dae/issues/171#issuecomment-1624840790

**Comment by Karmylr** [comment]
加`pname(dnsmasq) -> must_direct`解决了

**Comment by mzz2017** [comment]
上游不要写 dnsmasq

**Comment by Karmylr** [comment]
> 上游不要写 dnsmasq

dae的upstream没有dnsmasq

**Comment by Karmylr** [comment]
取消勾选dnsmasq的dns重定向解决了
