### ISSUE TITLE
[Support Request] 在OpenWrt上开启dae之后无法正常使用DHCP

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#293]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

在OpenWrt上开启dae之后无法正常使用DHCP。关闭后可以正常下发DHCP

### Current Behavior

无法使用DHCP

### Expected Behavior

能正常使用DHCP

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
@Karmylr 贴一下 routing

**Comment by Karmylr** [comment]
@mzz2017 
[routing.txt](https://github.com/daeuniverse/dae/files/12387030/routing.txt)

**Comment by mzz2017** [comment]
@Karmylr 你把 sip(geoip:private)->direct 放最前面

**Comment by Karmylr** [comment]
`sip(geoip: private) -> direct`会导致无法科学

**Comment by mzz2017** [comment]
@Karmylr 哦说错了，是 dip

**Comment by Karmylr** [comment]
解决了，谢谢
