### ISSUE TITLE
[Support Request] 无法使用ShadowsocksR节点

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#296]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

无法使用ssr节点

### Current Behavior

除了telegram，其他国外网站无法访问

### Expected Behavior

正常科学上网

### Steps to Reproduce

1、导入SSR节点
2、开启daed

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

### Anything else?

log:
```
time="Aug 20 12:07:23" level=debug msg="Rewrite dial target to domain" from="104.18.239.99:443" to="www.speedtest.net:443"
time="Aug 20 12:07:23" level=warning msg="handleConn: failed to dial 104.18.239.99:443: failed to select dialer from group proxy (tcp6): no alive dialer"
time="Aug 20 12:07:23" level=debug msg="Rewrite dial target to domain" from="104.18.239.99:443" to="www.speedtest.net:443"
time="Aug 20 12:07:23" level=warning msg="handleConn: failed to dial 104.18.239.99:443: failed to select dialer from group proxy (tcp6): no alive dialer"
```

**Comment by mzz2017** [comment]
@Karmylr ssr 不支持 udp，因此你需要将 dns 一节中的 googledns 改为 'tcp://8.8.8.8:53' 或者 'tcp+udp://8.8.8.8:53'

**Comment by Karmylr** [comment]
```
ipversion_prefer: 4
upstream {
  alidns: 'udp://223.5.5.5:53'
  googledns: 'tcp://8.8.8.8:53'
}
routing {
  request {
    qname(geosite: cn) -> alidns
    fallback: googledns
  }
}
```

还是无法科学

**Comment by TnZzZHlp** [comment]
> ```
> ipversion_prefer: 4
> upstream {
>   alidns: 'udp://223.5.5.5:53'
>   googledns: 'tcp://8.8.8.8:53'
> }
> routing {
>   request {
>     qname(geosite: cn) -> alidns
>     fallback: googledns
>   }
> }
> ```
> 
> 还是无法科学

看下节点连通性检测部分配置

**Comment by Karmylr** [comment]
> > ```
> > ipversion_prefer: 4
> > upstream {
> >   alidns: 'udp://223.5.5.5:53'
> >   googledns: 'tcp://8.8.8.8:53'
> > }
> > routing {
> >   request {
> >     qname(geosite: cn) -> alidns
> >     fallback: googledns
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还是无法科学
> 
> 看下节点连通性检测部分配置

![image](https://github.com/daeuniverse/dae/assets/69903376/fe3d10de-5a6e-4a44-bb4f-adc005f22682)

**Comment by TnZzZHlp** [comment]
> > > ```
> > > ipversion_prefer: 4
> > > upstream {
> > >   alidns: 'udp://223.5.5.5:53'
> > >   googledns: 'tcp://8.8.8.8:53'
> > > }
> > > routing {
> > >   request {
> > >     qname(geosite: cn) -> alidns
> > >     fallback: googledns
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 还是无法科学
> > 
> > 
> > 看下节点连通性检测部分配置
> 
> ![image](https://user-images.githubusercontent.com/69903376/262016716-fe3d10de-5a6e-4a44-bb4f-adc005f22682.png)

试试tcp部分只保留最上面那条，然后重启dae试试

**Comment by Karmylr** [comment]
> > > > ```
> > > > ipversion_prefer: 4
> > > > upstream {
> > > >   alidns: 'udp://223.5.5.5:53'
> > > >   googledns: 'tcp://8.8.8.8:53'
> > > > }
> > > > routing {
> > > >   request {
> > > >     qname(geosite: cn) -> alidns
> > > >     fallback: googledns
> > > >   }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 还是无法科学
> > > 
> > > 
> > > 看下节点连通性检测部分配置
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69903376/262016716-fe3d10de-5a6e-4a44-bb4f-adc005f22682.png)
> 
> 试试tcp部分只保留最上面那条，然后重启dae试试

还是不行

**Comment by TnZzZHlp** [comment]
我之前也是跟你同样的问题 后来我把 tcp连通性检测那里只保留 http://cp.cloudflare.com/generate_204 就好了，如果连通性检测失败会把对应的节点禁用掉，所以日志就会显示 no alive dialer，你可以参考一下我的配置试试。或者真的有可能你的节点连不上
`{
  "id": "Y3Vyc29yMQ",
  "name": "global",
  "selected": true,
  "global": {
    "logLevel": "info",
    "tproxyPort": 65530,
    "allowInsecure": false,
    "checkInterval": "30s",
    "checkTolerance": "20ms",
    "lanInterface": [
      "br-lan"
    ],
    "wanInterface": [
      "auto"
    ],
    "udpCheckDns": [
      "1.1.1.1:53"
    ],
    "tcpCheckUrl": [
      "http://cp.cloudflare.com/generate_204"
    ],
    "dialMode": "domain",
    "tcpCheckHttpMethod": "HEAD",
    "disableWaitingNetwork": false,
    "autoConfigKernelParameter": true,
    "sniffingTimeout": "100ms",
    "tlsImplementation": "utls",
    "utlsImitate": "chrome_auto",
    "tproxyPortProtect": true
  }
}`

**Comment by TnZzZHlp** [comment]
可以参考一下这个issue
#290

**Comment by Karmylr** [comment]
使用SSR节点时的日志：
```
time="Sep 02 10:42:56" level=debug msg="Connectivity Check" avg_10=225ms last=232ms mov_avg=170ms network="udp4(DNS)" node="4.[CT/CM]香港 09"
time="Sep 02 10:42:56" level=debug msg="Connectivity Check" avg_10=5.124s last=248ms mov_avg=2.624s network=tcp4 node="4.[CT/CM]香港 09"
time="Sep 02 10:42:56" level=info msg="[NOT ALIVE --tcp4-> ALIVE]" dialer="4.[CT/CM]香港 09" group="tg_ipv4"
time="Sep 02 10:42:56" level=debug msg="Connectivity Check Failed" err="invalid ivLen:12, actual length:0: EOF" network="tcp4(DNS)" node="4.[CT/CM]香港 09"
```

**Comment by mzz2017** [comment]
> 除了telegram，其他国外网站无法访问

你是 openwrt?

 https://github.com/daeuniverse/dae/issues/171#issuecomment-1624840790

**Comment by Karmylr** [comment]
> > 除了telegram，其他国外网站无法访问
> 
> 你是 openwrt?
> 
> [#171 (comment)](https://github.com/daeuniverse/dae/issues/171#issuecomment-1624840790)

现在用SSR电报也没法联网了

**Comment by Karmylr** [comment]
用Debian运行也是只有ssr节点用不了

**Comment by Karmylr** [comment]
ss节点，用了 https://github.com/daeuniverse/dae/issues/171#issuecomment-1624840790 的方法，还是国内正常，国外只有电报能用。dns配置：
```
ipversion_prefer: 4
upstream {
  ISPDNS: 'udp://218.85.157.99:53'
  GoogleDNS: 'tcp://8.8.4.4:53'
}
routing {
  request {
    qname(geosite: cn) -> ISPDNS
    fallback: GoogleDNS
  }
}
```

**Comment by Karmylr** [comment]
```
time="Sep 24 09:36:21" level=info msg="192.168.2.218:9057 <-> 172.217.175.4:443" dialer=direct dscp=0 ip="172.217.175.4:443" mac="90:76:9f:b2:fd:52" network=tcp4 outbound=direct pid=0 pname= policy=fixed sniffed=www.google.com
time="Sep 24 09:36:27" level=warning msg="handlePkt: failed to read from: 192.168.2.8:53 (dialer: direct): read udp [::]:50791: i/o timeout"
```
