### ISSUE TITLE
[Enhancement] Run as a system user instead of root in systemd service

### ISSUE THREAD

**Issue by A1ca7raz** [daeuniverse/dae#299]
### Improvement Suggestion

Specify a system user such as dae and grant necessary capabilities in the service.

### Potential Benefits

It is safer.

**Comment by mzz2017** [comment]
@A1ca7raz It is not possible because root is needed for inserting ebpf programs into linux kernel.

**Comment by yqlbu** [comment]
@A1ca7raz This is indeed a good suggestion. We will come up with a better solution.
