### ISSUE TITLE
[Feature Request] DNS-over-http/3 (DoH3) support request

### ISSUE THREAD

**Issue by nicholas-opensource** [daeuniverse/dae#321]
### Greetings

DNS-over-HTTP/3 (DoH3) and DNS-over-QUIC (DoQ) are standardized protocols now. They are the successors of DNS-over-HTTPS (DoH) and DNS-over-TLS (DoT), which were also secure but had some drawbacks.
Finding the right balance between security, speed and performance has always been a challenge for DNS protocols. In the past, we have seen many attempts to strike a balance, such as EDNS/DNSSEC, DNSCrypt, DoT/DoH, etc. They were all great innovations when they came out, but now they are falling behind.
DoH3 is faster than DoT/DoH, as it uses 0-RTT or a single round-trip handshake, while DoT/DoH needs at least 2.5-RTT at the first time. DoH3 also has many benefits from QUIC and UDP. DoH3 is more secure than a standard DNS protocol of UDP53, and it does not sacrifice much performance.
Many major DNS servers, such as Cloudflare, Google, NextDNS, and especially AliDNS, support DoH3.
```
h3://dns.alidns.com/dns-query
```
With the success of the `juicity` protocol, I think adding support for DoH3 should be considered (no need for high priority).

### Feature Request

DNS-over-HTTP/3 (DoH3) support in the DNS section

### Use Cases

```
dns {
    upstream {
        alidns: 'h3://dns.alidns.com/dns-query'
        alidns-with-ip: 'h3://223.5.5.5/dns-query'
    }
}
```

### Potential Benefits

Some references:
https://security.googleblog.com/2022/07/dns-over-http3-in-android.html
https://www.securityweek.com/google-introduces-dns-over-http3-android/
https://www.linkedin.com/advice/0/what-benefits-drawbacks-using-http3-over-http2-skills-informatics

**Comment by Kurokosama** [comment]
This is a super nice feature to have (
