### ISSUE TITLE
[Support Request] It's Possible to force disable Node connectivity check?

### ISSUE THREAD

**Issue by ZhiShengYuan** [daeuniverse/dae#324]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

I hope to be able to disable the Node connectivity check for the following reasons:

When network Node connectivity check is enabled, even if my node supports IPv6 (socks5 proxy), dae may think that my node does not support it, resulting in issues such as 'level=warning msg="handleConn: failed to dial []:80: failed to select dialer from group tcp (tcp6): no alive dialer.'

Regular requests initiated by availability checks can potentially become a recognizable pattern.

When only a single node is available, availability checks may lead to the overall network becoming unusable.
So I hope there is a way to disable it

### Current Behavior

none

### Expected Behavior

none

### Steps to Reproduce

none

### Environment

- **Dae version (dae version v0.3.0)**:

### Anything else?

none

**Comment by mzz2017** [comment]
@ZhiShengYuan policy: fixed(0)

**Comment by ZhiShengYuan** [comment]
> fixed(0)

When I have many completely equivalent nodes, what should I do?

**Comment by ZhiShengYuan** [comment]
> @ZhiShengYuan policy: fixed(0)


Although it's possible to run a load balancer locally to solve the problem, it may not be as elegant, even though it works.
