### ISSUE TITLE
[Enhancement] Support use system timezone or set timezone when log

### ISSUE THREAD

**Issue by EkkoG** [daeuniverse/dae#326]
### Improvement Suggestion

For now, write to log file using UTC timezone and can not change by config, I see dae uses logrus to print log, maybe we need to create a custom formatter to make it work[[1]](https://github.com/Sirupsen/logrus/issues/293)

### Potential Benefits

Better readability

**Comment by yqlbu** [comment]
@EkkoG Have you tried updating your system timezone?

**Comment by EkkoG** [comment]
> @EkkoG Have you tried updating your system timezone?

Yes, my system timezone is UTC+8

<img width="317" alt="CleanShot 2023-09-10 at 23 26 20@2x" src="https://github.com/daeuniverse/dae/assets/3138493/dae3baf7-f328-4c91-a28b-c6d585dd41d3">

**Comment by yqlbu** [comment]
Maybe we may try the following:

```go
log.SetFormatter(&log.JSONFormatter{})
```

**Comment by yqlbu** [comment]
We may try the following:

```go
log.SetFormatter(&log.JSONFormatter{})
```

**Comment by yqlbu** [comment]
Link to discussion #345. @EkkoG Shall we close this issue?
