### ISSUE TITLE
[Support Request] 手机端什么时候能支持Neko link？

### ISSUE THREAD

**Issue by yunmi323** [daeuniverse/dae#331]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

手机端什么时候能支持Neko link？pc端支持手机端竟然不支持，warp用Neko link 做订阅真香，望手机适配一下

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by MarksonHon** [comment]
什么手机端？dae目前还没被移植到任何Android设备
