### ISSUE TITLE
[Bug Report] 没法用Shadowsocks节点

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#336]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

使用ss节点，国内网站能正常访问，国外网站无法访问。但是 telegram 能正常使用。已经按照https://github.com/daeuniverse/dae/issues/171#issuecomment-1624840790 的方法设置好了dnsmasq，只有ss和ssr节点有问题

### Expected Behavior

能正常访问国外网站

### Anything else?

logs:
```
time="Sep 24 09:36:21" level=info msg="192.168.2.218:9057 <-> 172.217.175.4:443" dialer=direct dscp=0 ip="172.217.175.4:443" mac="90:76:9f:b2:fd:52" network=tcp4 outbound=direct pid=0 pname= policy=fixed sniffed=www.google.com
time="Sep 24 09:36:27" level=warning msg="handlePkt: failed to read from: 192.168.2.8:53 (dialer: direct): read udp [::]:50791: i/o timeout"
```

**Comment by Karmylr** [comment]
直接拖动订阅出来的机场标签进群组（相当于把所有节点都放进群组里）就能正常使用，拖入单个可用节点就不行。可能是因为联通性测试失败而被禁用了？

**Comment by yqlbu** [comment]
Please fill in a title for this issue.

**Comment by Karmylr** [comment]
已有他人复现

**Comment by Karmylr** [comment]
早就改成 tcp 了

**Comment by Karmylr** [comment]
> 你的ss多半不支持udp，把dns改里面的地址，把googledns改成tcp://8.8.8.8:53

连通性检测方式改成GET就解决了。应该是HEAD方式有问题

**Comment by KSAMNI** [comment]
解决了吗？我从glados提取的ss节点也是无法使用，全部都是失败
