### ISSUE TITLE
[Bug Report] !mac 判断异常

### ISSUE THREAD

**Issue by EkkoG** [daeuniverse/dae#339]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

routing 配置如下

mac('2c:9e:00:7a:26:38') -> direct
!mac('2c:9e:00:7a:26:38') -> direct
dip(geoip:private) -> direct
fallback: proxy

有流量走到 fallback

### Expected Behavior

所有流量都直连，没有走到 fallback 的

### Steps to Reproduce

使用配置运行 dae 即可

### Environment

- **Dae version (use `dae --version`)**: daed version 0.4.0rc1
- **OS (e.g `cat /etc/os-release`)**: ImmortalWrt 23.05.0-rc3 r26804-a3639e76d6
- **Kernel (e.g. `uname -a`)**: Linux ImmortalWrt 5.15.120 #0 SMP Mon Jul 24 10:07:07 2023 x86_64 GNU/Linux
- **Others**:

**Comment by mzz2017** [comment]
已复现问题

**Comment by cjwddtc** [comment]
这个问题怎么样了？要是这个有问题基本上pt用户就告别dae了吧，我都是docker的mac一过滤就好了，关键是ip过滤应付不了ipv6啊
