### ISSUE TITLE
[Support Request] 使用运行着dae的Debian 12作二级路由时无法访问国内网站

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#340]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

在作二级路由的Debian 12上安装了dae，但是只有国外的网站能访问。

**Comment by Karmylr** [comment]
解决了。启用 nftables 的 nat 就能转发流量了

**Comment by yqlbu** [comment]
@Karmylr Yes, it’s a known issue.

**Comment by kyleli666** [comment]
> 解决了。启用 nftables 的 nat 就能转发流量了

@Karmylr @yqlbu 我也有类似的问题，请教一下应该怎么设置nat？

**Comment by kyleli666** [comment]
> > > 解决了。启用 nftables 的 nat 就能转发流量了
> > 
> > 
> > @Karmylr @yqlbu 我也有类似的问题，请教一下应该怎么设置nat？
> 
> 请参考 https://access.redhat.com/documentation/zh-cn/red_hat_enterprise_linux/8/html/securing_networks/configuring-nat-using-nftables_getting-started-with-nftables 并且根据自身环境配置

我根据文章里的2.4.2节开启masquerade后，国内网站可以访问了。
```bash
nft add table nat
nft add chain nat postrouting { type nat hook postrouting priority 100 \; }
nft add rule nat postrouting oifname "ens3" masquerade
```
其中ens3替换为自己对应的网卡即可。

**Comment by fghwett** [comment]
感谢 我遇到了同样的问题，一开始的环境安装了1panel还不成功，后来重新用初始的debian12环境试了一下正常了。

**Comment by unaya** [comment]
我通过这篇文章解决了问题，供后来者参考
https://www.server-world.info/en/note?os=Ubuntu_22.04&p=ufw&f=2

**Comment by jjqtony** [comment]
使用linuxlite 6.6 无需nft和ufw配置

**Comment by weicaixian86** [comment]
> 我通过这篇文章解决了问题，供后来者参考 https://www.server-world.info/en/note?os=Ubuntu_22.04&p=ufw&f=2

兄弟你能不能把你执行的命令贴出来啊，那个文章看不懂啊。
