### ISSUE TITLE
[Feature Request] 增加端口分享的功能

### ISSUE THREAD

**Issue by kyleli666** [daeuniverse/dae#342]
### Feature Request

由于我需要同时使用透明代理+端口分享，所以希望能增加于v2rayA一样的端口分享的功能。

目前我只能同时开着daed和v2rayA，daed做透明代理，v2rayA仅开启端口分享，但这样我需要同时维护两套rules，比较麻烦。

### Use Cases

同时使用透明代理+端口代理的场合

### Potential Benefits

可以完全替代v2rayA

**Comment by mzz2017** [comment]
@kyleli666 可以拿glider自己开一个

**Comment by kyleli666** [comment]
> @kyleli666 可以拿glider自己开一个

Good idea! 我试试 谢谢

**Comment by kyleli666** [comment]
> @kyleli666 可以拿glider自己开一个

成功了，可以使用~谢谢！
这样至少不用开两个了~

**Comment by Faramitas** [comment]
> > @kyleli666 可以拿glider自己开一个
> 
> 成功了，[glider](https://github.com/nadoo/glider)可以成功代理~ 谢谢！ 这样至少不用开两个了~

可以求一下具体实现方式吗？我是在开dae同一天设备上开了一个socks5 server，后面routing不知道该怎么写了

**Comment by kyleli666** [comment]
@Faramitas 
我是在装daed的设备上安装glider，用最简单的配置，/etc/glider/glider.conf 如下
···ini
# Verbose mode, print logs
verbose=True
# listen on 8443, serve as http/socks5 proxy on the same port.
listen=:8443
···
由于daed会透明代理本机的网络请求，所以glider本身也被代理了。因此不需要什么特殊的routing，glider暴露出来的http/socks5端口就能直接作为代理使用了。
不知你是否是这个情况。

**Comment by Faramitas** [comment]
> @Faramitas 我是在装daed的设备上安装glider，用最简单的配置，/etc/glider/glider.conf 如下
> 
> ```ini
> # Verbose mode, print logs
> verbose=True
> # listen on 8443, serve as http/socks5 proxy on the same port.
> listen=:8443
> ```
> 
> 由于daed会透明代理本机的网络请求，所以glider本身也被代理了。因此不需要什么特殊的routing，glider暴露出来的http/socks5端口就能直接作为代理使用了。 不知你是否是这个情况。

我找到原因了，我是op旁路跑的daed和socks5 server，但是wan未设置，所以没有进站入口，我把wan设置与lan一样的口之后，就正常了
