### ISSUE TITLE
[Enhancement] Stop daebot's abuse behavior 停止 daebot 的要求刷星行为

### ISSUE THREAD

**Issue by pengw0048** [daeuniverse/dae#374]
### Improvement Suggestion

When an issue is opened in this repo, @daebot will mark it as won't fix and close the issue, and will only reopen it if the issue author stars the repo [[example](https://github.com/daeuniverse/dae/issues/363#issuecomment-1837060440)].

In my opinion, this is against the GitHub Acceptable Use Policies; in particular, [4. Spam and Inauthentic Activity on GitHub](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github):

> We do not allow content or activity on GitHub that is:
> ...
> rank abuse, such as automated starring or following;
> creation of or participation in secondary markets for the purpose of the proliferation of inauthentic activity;
> incentivized by (or incentivizes inauthentic engagement with) rewards such as cryptocurrency airdrops, tokens, credits, gifts or other give-aways.

While the bot's behavior is not directly listed as an example, I believe it is close enough to the essence of the above quoted items, and in reality constitutes a manipulation on the stars of the repo, giving the repo an unfair position, and therefore should be considered abuse.

I have reported this behavior to GitHub already, but also opening this issue to notify the repo owners and request that you stop this behavior.

### Potential Benefits

In my opinion this is an unacceptable behavior on GitHub. By removing it, issue authors will not be obliged to star the repo to submit legit issues, and the repo doesn't unfairly get an advantage in ranks and statistics.

---

Translated by ChatGPT 4:
改进建议
当在此仓库中打开一个问题时，@daebot 会将其标记为“不会修复”并关闭该问题，只有在问题作者收藏（star）该仓库后才会重新打开 [示例]。

在我看来，这违反了 GitHub 可接受使用政策；特别是第4条，GitHub 上的垃圾邮件和不真实活动：

我们不允许在 GitHub 上的内容或活动是：
...
滥用排名，如自动收藏或关注；
创建或参与次级市场以传播不真实活动；
激励（或激励与之相关的不真实参与）奖励，如加密货币空投、代币、积分、礼物或其他赠品。

虽然机器人的行为没有直接列为例子，但我认为它足够接近上述项目的本质，并在实际上构成了对仓库星标的操纵，给予仓库不公平的位置，因此应该被视为滥用。

我已经向 GitHub 报告了这种行为，但也开设了这个问题来通知仓库所有者，并要求您停止这种行为。

潜在好处
在我看来，这在 GitHub 上是不可接受的行为。通过移除它，问题作者就不必收藏仓库来提交合法问题，而且仓库也不会在排名和统计数据上不公平地获得优势。

**Comment by MarksonHon** [comment]
Feel free to report as you like, the behavior of bot has been shutdown
