### ISSUE TITLE
[Proposal] Let tproxy_wan_{egress,ingress} bpf work for forwarding traffic?

### ISSUE THREAD

**Issue by jschwinger233** [daeuniverse/dae#377]
### Proposal

For now `tproxy_wan_*` return packets to stack if skb->ingress_index !=0:

https://github.com/daeuniverse/dae/blob/a794c4ca61945a83732abac99b4b4ec276028882/control/kern/tproxy.c#L1585-L1590

This means this pair of bpf prog handle "from_host" packets only, rather than "forwarding" ones.

I understand it's `tproxy_lan_*`'s responsibility to take care of forwarding traffic, I just feel compelled to point it out:
1. It's probably feasible to have `tproxy_wan_*` also work for forwarding packets, see "Implementation" section below.
2. We could benefit from this improvement, see "Potential Benefits" section below.

All I want to say is, maybe it's something worth a try? Feel free to say no if something crucial I missed.

### Potential Benefits

Benefits are on top of hypothesis that we can absolutely remove "tproxy_lan_*` once and for all. I'm not 100% confident about that, but if it turns out to be possible:
1. Users no longer have to configure `lan_interface`. As lan iface can't be automatically detected, it might be unclear to some users about when we should configure it with what value.
2. Code complexity can be reduced to huge extent.

### Implementation

I only took a look at TCP datapath, so let me start from there.
(I am aware there is UDP (and even IPv6 NDP) handling inside `lan_*` bpf, no idea if they can be ported to wan bpf prog.)

(Also it's on top of https://github.com/daeuniverse/dae/issues/375)

Outbound: 
1. We remove `skb->ingress_ifindex != 0` check in `wan_*`
2. Then dae tproxy's forward traffic will end up in the infinite loop. To avoid that, we set a special mark to skb (e.g. 0xb00) which is sent from tproxy. This can be done by `setsocketopt(SOL_SOCKET, SO_MARK)` in dae proxy.
3. Then `wan_*` bpf can exclude tproxy traffic via special mark.
4. Remove relevant code from `lan_*`.

Inbound:
No issue, just return packets to stack.

One thing need to mention is, transferring duty from `lan_*` to `wan_*` also leads to additional stack traversal: previously, skb can be bpf_sk_assigned to dae sockets once reaching lan_interface; with this change, skb must be routed to wan_interface. This can affect performance I presume, not sure how much it can be. A quick improvement is to `bpf_redirect` from lan_interface to wan_interface so as to avoid stack traversal.

**Comment by mzz2017** [comment]
@jschwinger233 一方面，wan 和 lan 分离是用户的一部分需求，有的人想代理本机，有的人不希望；有的人想代理局域网，有的人不希望。
另一方面，wan 目前的实现是两次 nat，我认为不是一个好的方案，所以不是很想让这个方案把 lan 的替换掉。

**Comment by mzz2017** [comment]
@jschwinger233 另一个问题是，wan 口不一定是以太口，例如它可能是 pppoe，对于它的报文处理是不兼容的。但 lan 口一般都是以太口，这使得 dae 可以工作在局域网转发。

**Comment by jschwinger233** [comment]
合理，感谢解答。
