### ISSUE TITLE
关于在树莓派上吃鹅的问题

### ISSUE THREAD

**Issue by nsnake** [daeuniverse/dae#385]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

我尝试在树莓派3B上使用Raspberry OS来运吃鹅，结果发现该系统上无法运行
出错信息
apply CO-RE relocations: load kernel spec: no BTF found for kernel version 6.1.0-rpi7-rpi-v7: not supported

支持查看内核支持的结果
```
(zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) | grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|NET_EGRESS|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED is not set'
gzip: /proc/config.gz: No such file or directory
cat: /boot/config: No such file or directory
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_ACT=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
```
我想知道在arm上有哪些系统是直接支持不需要自己编译内核的呢。
谢谢了。

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
armbian 可以用 https://github.com/daeuniverse/armbian-btf-kernel 这个内核（但这个仓库有半年没有维护了）。

可以提交 issue 让树莓派那边跟进 btf，连 alpine 都支持好了。

**Comment by MarksonHon** [comment]
其实可以试试Alpine的树莓派镜像

**Comment by nsnake** [comment]
已经测试了树莓派和ubuntu不支持
fedora系统可以直接支持
