### ISSUE TITLE
[Bug Report] WAN IPv6 UDP dropped due to SKB_DROP_REASON_PKT_TOO_SMALL

### ISSUE THREAD

**Issue by jschwinger233** [daeuniverse/dae#387]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

`dig @2001:4860:4860::8844 one.one.one.one` couldn't get response.

dae trace log says it never receive any IPv6 UDP request.

`pwru` tracing says packets are dropped by kernel due to SKB_DROP_REASON_PKT_TOO_SMALL:
```
0xffff8a63853a3600      3     [dig(52934)]                udpv6_rcv netns=4026534242 mark=0x0 iface=16(eth0) proto=0x86dd mtu=1500 len=64 [2001:4860:4860::8844]:46396->[2001:db8::3]:12345(udp)
0xffff8a63853a3600      3     [dig(52934)]           __udp6_lib_rcv netns=4026534242 mark=0x0 iface=16(eth0) proto=0x86dd mtu=1500 len=64 [2001:4860:4860::8844]:46396->[2001:db8::3]:12345(udp)
0xffff8a63853a3600      3     [dig(52934)] kfree_skb_reason(SKB_DROP_REASON_PKT_TOO_SMALL) netns=4026534242 mark=0x0 iface=16(eth0) proto=0x86dd mtu=1500 len=64 [2001:4860:4860::8844]:46396->[2001:db8::3]:12345(udp)
```

Kernel source says skb->len doesn't match udp->len:
https://github.com/torvalds/linux/blob/v6.5/net/ipv6/udp.c#L969-L970

I suspect it's caused by `adjust_ipv4_len` during `tproxy_wan_egress`. It looks even IPv6 UDP packets are handled by `adjust_ipv4_len`, not sure what consequence it is.

**Comment by mzz2017** [comment]
Thank you so much for investgating it. It is related to #102.

**Comment by mzz2017** [comment]
@jschwinger233 If we use bpf_assign, this problem should be bypass.
