### ISSUE TITLE
[Bug Report] 在aarch64上启动时间过长

### ISSUE THREAD

**Issue by nsnake** [daeuniverse/dae#413]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

OS使用的是aarch64版的fedora39 workstation
关闭了selinux和禁用了ipv6
dae 0.4和0.5都使用了
以下是启动时的一些信息
`[root@fedora ~]# /usr/bin/dae -c /etc/dae/config.dae run
[Jan 04 21:23:20]  INFO Include config files: [/etc/dae/config.dae]
[Jan 04 21:23:20]  INFO Loading eBPF programs and maps into the kernel...
[Jan 04 21:23:20]  INFO The loading process takes about 120MB free memory, which will be released after loading. Insufficient memory will cause loading failure.
[Jan 04 21:24:12]  INFO Loaded eBPF programs and maps
[Jan 04 21:24:12]  WARN IpRouteAdd: Bad IPv6 support. Perhaps your machine disabled IPv6.
[Jan 04 21:24:12]  INFO Bind to LAN: eth0
`
可以看到21:23:20到04 21:24:12的Loaded eBPF programs and maps花费了将近一分钟的时间。

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
@nsnake 启动时间和硬件性能有关系，我的软路由也启动挺慢，我的arm64的苹果虚拟机刷刷快

**Comment by nsnake** [comment]
> @nsnake 启动时间和硬件性能有关系，我的软路由也启动挺慢，我的arm64的苹果虚拟机刷刷快

奇怪的是之前用fedora39  server在同样硬件的情况下启动的很快。
workstation进行过系统更新，不太清楚是不是因为新的内核的原因导致的。晚点我在弄个原版的在测试一下

**Comment by nsnake** [comment]
换成fedora server 40后启动正常了，只是在VPN下本地出局失效，代理可以出局，但不属于该问题了，所以关闭
