### ISSUE TITLE
Address already in use :::3000 at Server

### ISSUE THREAD

**Issue by hedove** [daeuniverse/dae#415]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [x] Is it your first time sumbitting an issue

### Support Request

root@ubuntu:/data# cat /var/log/daed_stderr.log
⨯ Failed to start server
Error: listen EADDRINUSE: address already in use :::3000
at Server.setupListenHandle [as _listen2] (node:net:1872:16)
at listenInCluster (node:net:1920:12)
at Server.listen (node:net:2008:7)
at /opt/daed/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:268:16
at new Promise ()
at startServer (/opt/daed/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:181:11)
at nextStart (/opt/daed/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/cli/next-start.js:50:40)
at /opt/daed/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/bin/next:150:54
at async main (/opt/daed/node_modules/.pnpm/next@14.0.3_@babel+core@7.23.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/bin/next:150:5) {
code: 'EADDRINUSE',
errno: -98,
syscall: 'listen',
address: '::',
port: 3000
}

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      798/sshd: /usr/sbin 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      688/systemd-resolve 
tcp6       0      0 :::2023                 :::*                    LISTEN      2086/dae-wing       
tcp6       0      0 :::1080                 :::*                    LISTEN      731/sing-box        
tcp6       0      0 :::22                   :::*                    LISTEN      798/sshd: /usr/sbin 
tcp6       0      0 :::3000                 :::*                    LISTEN      3653/next-server    
tcp6       0      0 :::12345                :::*                    LISTEN      2086/dae-wing   

### Expected Behavior

root@ubuntu:/opt/daed# systemctl status daed.service
● daed.service - daed Service
     Loaded: loaded (/etc/systemd/system/daed.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-01-06 09:00:19 UTC; 2h 58min ago
       Docs: https://github.com/daeuniverse/daed-revived-next
   Main PID: 3636 (node)
      Tasks: 31 (limit: 18653)
     Memory: 105.5M
     CGroup: /system.slice/daed.service
             ├─3636 node /usr/bin/pnpm start
             ├─3652 sh -c next start
             └─3653 next-server

Jan 06 09:00:19 ubuntu systemd[1]: Started daed Service.

### Environment

ubuntu 20.04

**Comment by mzz2017** [comment]
@hedove 提错 repo 了

**Comment by hedove** [comment]
> @hedove提错 repo 了

提错是什么意思呢？

**Comment by MarksonHon** [comment]
这里是dae的仓库，不是daed或daed-next的仓库

**Comment by hedove** [comment]
> 这里是dae的仓库，不是daed或daed-revived-next的仓库

感谢，我已经过去问了。
