### ISSUE TITLE
[Enhancement] 只对指定的域名优先返回v4/v6

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#428]
### Improvement Suggestion

为指定的域名单独设置ipversion_prefer

### Potential Benefits

运行着录播机的debian经常需要换IP来防止风控，需要v6优先
pve和debian的apt源必须要v4优先才能正常update和install

**Comment by mzz2017** [comment]
@Karmylr 你直接把特定域名的qtype(a) reject 了不就好了

**Comment by Karmylr** [comment]
有道理 我试试
