### ISSUE TITLE
i225/226 NIC PVE Hardware passthrough

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#43]
If you are using Intel i225/226 NIC, you may encounter the problem that the client cannot get the DNS IP after enabling the NIC hardware passthrough feature under PVE.

Solution
1. Install ethtool
apt install ethtool
2. Add command line to /etc/systemd/system/dae.service file
[Service]
ExecStartPre=/usr/sbin/ethtool -K [Your network interface name] tx-checksum-ip-generic off

Please add this solution to the Troubleshooting Doc. Thank you.

**Comment by mzz2017** [comment]
Thanks. I'll add a link point to here.

However, turning off tx-checksum-ip-generic will lower the performance of sending.

I don't know whether it has better performance than non-passthrough case.

**Comment by BOBINIUNIU** [comment]
Yes, turning off tx-checksum-ip-generic will impact performance for network packet sending, but CPU usage is lower than the E1000 and Realtek NIC models.

**Comment by mzz2017** [comment]
@BOBINIUNIU May I ask, is it possible to passthrough NIC to multiple VM?

**Comment by BOBINIUNIU** [comment]
> 

No. Each passthrough network interface can only be used on one VM. For example, if your PC have 4 network interfaces, you can only use them on maximum of 3 VMs. PVE will not be accessible if you enable passthrough on the management interface.
