### ISSUE TITLE
[Bug Report] failed to fetch google fonts

### ISSUE THREAD

**Issue by hronro** [daeuniverse/dae#430]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

Background: I built my own router based on Alpine Linux and installed dae to enable transparent-proxy functionality for all devices on my LAN network.

I noticed that certain websites were loading very slowly in my browser when dae was enabled on the router.

Upon investigation, I discovered that this issue was caused by a pending request for Google Fonts, which eventually failed due to a timeout.

![CleanShot 2024-01-18 at 06 39 25@2x](https://github.com/daeuniverse/dae/assets/15059605/921b3232-46db-4ade-9f58-bc21884bc65d)

I also attempted to retrieve the same resource on another Linux machine using curl, and encountered the same result.

![CleanShot 2024-01-18 at 06 47 57@2x](https://github.com/daeuniverse/dae/assets/15059605/3d952257-0509-4ae8-ba32-d6a79f27765e)

Additionally, I verified the IP address of that resource in the log of the curl command (142.251.220.74), confirming that it does indeed belong to Google. Therefore, I conclude that this issue is not caused by DNS poisoning.

In the end, I tried to turn off dae in my router and open Quantumult X on my Mac using the same proxy server, and the Google font could be fetched immediately, so I guess it's not a problem with my proxy server.

### Expected Behavior

The Google fonts should be fetched without a timeout.

### Environment

- **Dae version (use `dae --version`)**: v0.5.0
- **OS (e.g `cat /etc/os-release`)**: Alpine Linux v3.19
- **Kernel (e.g. `uname -a`)**: 6.6.12-0-lts
- **Others**:

**Comment by mzz2017** [comment]
Do you know routing and dns routing functions of dae?

**Comment by hronro** [comment]
@mzz2017 Of course I know, but it doesn't explain why are there only problems with Google fonts and not with any other resources. I didn't add anything specific to the Google fonts in the `config.dae`.
