### ISSUE TITLE
[Feature Request] DNS group

### ISSUE THREAD

**Issue by jeffguorg** [daeuniverse/dae#431]
### Feature Request

just like node group, a dns server can be placed into a dns group and detect whether it is alive. 

### Use Cases

some dns upstream has strict qos by source address, and there is a case that dns upstream can fail. 

in such cases, when one dns upstream stopped to respond to dae, we should switch to another.

### Potential Benefits

for routers in office or a home with many devices of different vendors,  each vendor or device has its own cloud services and domains like captive portal, syncing, third party apps and services. thus when the devices are connected to a network, a lot of dns request will be made. qos of upstream dns services can cause problem when massive dns request is sent.

and in some area or for some dns upstream, dns services can be sometimes unstable.

dns group can mitigate the problem and benifit to such cases

**Comment by mzz2017** [comment]
@jeffguorg I believe this enterprise level requirement can be achieved through nesting rather than seeking all-in-one of dae.
