### ISSUE TITLE
[Bug Report] Devices with ipv6 address can't connect, with dae on openwrt

### ISSUE THREAD

**Issue by Mapleshade20** [daeuniverse/dae#432]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

无法访问国外网站（见日志）

### Expected Behavior

正常情况下：用ipv4连接远程v4代理服务器以访问google等国外网站，用ipv6/ipv4直连任何中国网站和国外的仅ipv6网站

### Steps to Reproduce

Visit google.com on my computer

<img width="455" alt="屏幕截图 2024-01-19 130133" src="https://github.com/daeuniverse/dae/assets/62641761/21328d1b-f356-4464-88dc-0c3d88a420ee">

DHCP 选项 （通告）6, 223.5.5.5
通告的 IPv6 DNS 服务器 2400:3200::1

### Environment

- **Dae version (use `dae --version`)**: personally compiled (using [mzz/optimize_add_53_anyfrom_whitelist](https://github.com/daeuniverse/dae/tree/mzz/optimize_add_53_anyfrom_whitelist))
- **OS (e.g `cat /etc/os-release`)**: ImmortalWrt 23.05.1
- **Kernel (e.g. `uname -a`)**: Linux ImmortalWrt 5.15.137 x86_64 GNU/Linux
- **Others**: N/A

### Anything else?

全部日志和dae配置
Full log & Dae configuration
https://paste.fo/1f501ea389db

**Comment by mzz2017** [comment]
那你加了 ipversion(6)->direct 了吗

**Comment by mzz2017** [comment]
@Mapleshade20 看起来你没有关掉 dnsmasq 的重定向
