### ISSUE TITLE
[Feature Request] Auto update subscribe

### ISSUE THREAD

**Issue by Mitsuhaxy** [daeuniverse/dae#436]
### Feature Request

功能请求：增加内置订阅更新功能，可以设置固定间隔时间后更新订阅，可以使用db记录上次更新时间，避免重启dae后多次拉取订阅链接。
希望开发者可以考虑这个提议。

**Comment by eskimokk** [comment]
附议

**Comment by mzz2017** [comment]
请自行考虑使用 crontab 配合
dae reload
或 subscription 中的 file://
实现功能。
