### ISSUE TITLE
[Bug Report] 使用外部DNS服务的问题还是没有修复

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#442]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Steps to Reproduce

经测试，如果上游DNS设置的是1.1.1.1，走UDP 53端口，工作正常。如果设置的是Doh https://1.1.1.1/dns-query
，走TCP 443 端口则无法通信。

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
@BOBINIUNIU 不要 bind wan 试试

**Comment by mzz2017** [comment]
@BOBINIUNIU 不 bindwan，找个国内的 doh 试试，毕竟国外的不 bindwan 就不通了

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU 不 bindwan，找个国内的 doh 试试，毕竟国外的不 bindwan 就不通了

如果不binwan，就等于是直连访问 https://1.1.1.1/dns-query，我先试一下吧

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU 不 bindwan，找个国内的 doh 试试，毕竟国外的不 bindwan 就不通了

不绑wan就没有问题，但是DNS请求就是直连了吧。我的配置是国内普通UDP 53, 外网 DoH

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU 不 bindwan，找个国内的 doh 试试，毕竟国外的不 bindwan 就不通了

把WAN绑定去掉就可以了，但是这样DNS是走的直连吗？我的设置是国内UDP 53, 国外通过代理走DoH

**Comment by mzz2017** [comment]
@BOBINIUNIU 没事，就确认一下问题，之后出个 pr 给你试试

**Comment by mzz2017** [comment]
https://github.com/daeuniverse/dae/pull/447

可以帮忙确认一下该 pr 是否修复吗？ @BOBINIUNIU

**Comment by BOBINIUNIU** [comment]
DNS的问题解决了，但是代理失效了，访问所有网站都是直连了

**Comment by jschwinger233** [comment]
有兴趣开个 tmate 让我远程调试吗，毕竟你这个问题拖了很久了大家还是不知道是什么原因。

**Comment by BOBINIUNIU** [comment]
没报错，日志正常。你有debian12的环境吗？我把所有的配置文件发给你很容易就能复现这个问题。


> 有兴趣开个 tmate 让我远程调试吗，毕竟你这个问题拖了很久了大家还是不知道是什么原因。

**Comment by jschwinger233** [comment]
无 debian，不过先试试你的配置吧。邮箱地址在我github账号页面。

**Comment by BOBINIUNIU** [comment]
> 无 debian，不过先试试你的配置吧。邮箱地址在我github账号页面。

已发送，请查收

**Comment by jschwinger233** [comment]
谢谢，看了一眼配置可能知道问题了，我应该 return TC_ACT_PIPE 而不是 TC_ACT_OK，才能正确处理 wan+lan 同一网卡的情况。

**Comment by BOBINIUNIU** [comment]
> 谢谢，看了一眼配置可能知道问题了，我应该 return TC_ACT_PIPE 而不是 TC_ACT_OK，才能正确处理 wan+lan 同一网卡的情况。

Good luck ：）

**Comment by jschwinger233** [comment]
再试试 https://github.com/daeuniverse/dae/pull/447 ?

**Comment by BOBINIUNIU** [comment]
> 再试试 #447 ?

DNS又不通了。问题出在wan 绑定上，不绑wan是可以工作的。如果可以，请直接发送编译好的文件给我。
如果你没有环境，我明天装一个虚拟机，给你开远程。

**Comment by jschwinger233** [comment]
如果你用的是那个 PR build，也可以运行 `sudo ./dae-linux-x86_64 trace -4 -p udp -P 53 -o trace.log` 来抓包。它会打印一个

```
attaching kprobes: 1704/1704
start tracing
```

的进度显示。等 attach 完成，出现了 start tracing，触发一次 DNS 查询，然后 ctrl-c 打断 dae trace，收集 trace.log 就行。打断之后 detach 会比较慢，是正常的。

**Comment by mzz2017** [comment]
@jschwinger233 是开着 dae 再运行这个命令对吧 cc @BOBINIUNIU

**Comment by BOBINIUNIU** [comment]
@jschwinger233 @mzz2017 
我已经搭建好了测试服务器，登录信息已经发送到两位的邮箱。

**Comment by BOBINIUNIU** [comment]
这个修改bpf: wan_ingress returns TC_ACK_PIPE 修复了问题，我昨天编译的时候没有把这个PR更新

**Comment by jschwinger233** [comment]
谢谢。PR build 可以在 PR 页面点 “Checks” -> “PR Build(Preview)”，下拉可以找到所有架构的二进制直接下载，如 https://github.com/daeuniverse/dae/actions/runs/7740843296 ， 这样就不用自己编译了。

**Comment by BOBINIUNIU** [comment]
运行了几分钟后又出问题了，大佬们用我的服务器调试吧，登录信息已经发到邮箱了

**Comment by BOBINIUNIU** [comment]
> 谢谢。PR build 可以在 PR 页面点 “Checks” -> “PR Build(Preview)”，下拉可以找到所有架构的二进制直接下载，如 https://github.com/daeuniverse/dae/actions/runs/7740843296 ， 这样就不用自己编译了。

谢谢，以后不用自己编译了

**Comment by BOBINIUNIU** [comment]
配置文件加上auto_config_kernel_parameter: true 参数后工作正常了
