### ISSUE TITLE
[Bug Report] Capturing an incorrect DNS qname

### ISSUE THREAD

**Issue by douglarek** [daeuniverse/dae#448]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

dns settings:
```
dns {
    upstream {


        alidns: 'udp://dns.alidns.com:53'
        googledns: 'tcp+udp://dns.google.com:53'
    }
    routing {
        request {
            qname(suffix: api.miwifi.com) -> reject
            qname(geosite:cn) -> alidns
            qname(geosite:microsoft@cn) -> alidns
            # fallback is also called default.
            fallback: googledns
        }
    }
}
```

When I request `api.miwifi.com` and check the DAE log, it seems that there is an issue with the _qname during DNS resolution, causing DNS requests that should have been rejected to be resolved through the fallback DNS server.

dae log:

```
level=info msg="192.168.1.109:38729 <-> [2001:4860:4860::8888]:53" _qname=api.miwifi.com.lan. dialer="sg" dscp=0 mac="a0:e7:xx:xx:1f:8f" network="tcp6(DNS)" outbound=sg pid=0 pname= policy=min_moving_avg qtype=A
level=info msg="192.168.1.109:38729 <-> [2001:4860:4860::8888]:53" _qname=api.miwifi.com.lan. dialer="sg" dscp=0 mac="a0:e7:xx:xx:1f:8f" network="tcp6(DNS)" outbound=sg pid=0 pname= policy=min_moving_avg qtype=AAAA
```

### Expected Behavior

It seems that it shouldn't be DNS resolved, or at least it shouldn't be resolved through the proxy.

### Steps to Reproduce

You can simply use the DNS configuration mentioned above.

### Environment

- **Dae version (use `dae --version`)**:
```
dae version 0.5.1
go runtime go1.21.6 linux/arm64
Copyright (c) 2022-2024 @daeuniverse
License GNU AGPLv3 <https://github.com/daeuniverse/dae/blob/main/LICENSE>
```
- **OS (e.g `cat /etc/os-release`)**:
openwrt 23.05
- **Kernel (e.g. `uname -a`)**:
5.15
- **Others**:

**Comment by mzz2017** [comment]
@douglarek it's up to your dns routing, isn't it?

**Comment by mzz2017** [comment]
@douglarek It is not dae's bussiness. Google it.
