### ISSUE TITLE
[Workaround] 关于 Openwrt/ImmortalWrt 更新dae0.5.1后报 failed to add veth pair 的解决办法

### ISSUE THREAD

**Issue by github-xihe** [daeuniverse/dae#451]
### Summary

关于 Openwrt/ImmortalWrt 更新 dae0.5.1 后报 failed to add veth pair.

Workaround about `failed to add veth pair`.

## Platform

OpenWRT / ImmortalWRT

### Dae version

dae >=0.5.1

### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Anything else?

![photo_2024-01-31_23-56-33](https://github.com/daeuniverse/dae/assets/53401671/c8e4fa8a-892c-4c95-b430-5318967c30e4)

此报错 dae 启动不起来的原因为缺少 `kmod-veth`，软件包安装 `kmod-veth `即可。

The reason why dae cannot start is because of the lack of `kmod-veth`. You can install the `kmod-veth` package.

![image](https://github.com/daeuniverse/dae/assets/53401671/747a9159-ae39-4da8-8d8a-056129414464)

**Comment by Puqns67** [comment]
建议直接在文档中要求内核需要开启 `CONFIG_VETH` 配置项。
