### ISSUE TITLE
[Bug Report] Unable to compile trace/trace.go for arm64

### ISSUE THREAD

**Issue by douglarek** [daeuniverse/dae#453]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

#435 The implemented dae trace functionality seems unable to achieve cross-platform compilation. For example, it cannot compile packages for the arm64 architecture on amd64, and even fails to compile arm64 packages on arm64.

I found that the arm64 package compiled in GitHub Actions also encounters errors when compiling trace/trace.go, but it is simply skipped.

### Expected Behavior

Is this the intended behavior? However, according to the instructions in #435, it should support the arm64 architecture.

### Steps to Reproduce

`GOARCH=arm64 make`

### Environment

- **Dae version (use `dae --version`)**: the latest main branch
- **OS (e.g `cat /etc/os-release`)**: x86_64 linux
- **Kernel (e.g. `uname -a`)**: 6.7.2
- **Others**:

**Comment by jschwinger233** [comment]
@hero-intelligent it looks more like a successful build to me. Can you check your local file, I think there is a dae binary.

**Comment by jschwinger233** [comment]
@douglarek What error did you see when building on arm64?

**Comment by jschwinger233** [comment]
@douglarek Got it. This is because arm64 requires vmlinux-arm.h. I'll create a PR for it. Also will make https://github.com/daeuniverse/dae/pull/435#issuecomment-1913055090 happen.

**Comment by jschwinger233** [comment]
@hero-intelligent If you want to build dae with trace module, you have to specify `GOARCH=amd64` in command line (for now. will opt-out this hassle soon). Even if you don't, dae compiles as well, just without trace module.
