### ISSUE TITLE
[Bug Report] Alpine rc-service stop 行为不正常

### ISSUE THREAD

**Issue by eskimokk** [daeuniverse/dae#457]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

rc-service dae stop 之后 服务并没有被关掉，死灰复燃了。这就导致restart出错。

神奇的是，如果手动kill掉supervise-daemon后再rc-service dae start。这时再rc-service dae stop就没问题啦。

请看我后面的整个命令执行过程。

### Steps to Reproduce

```
alpinerc:~$ doas rc-service dae status
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/dae status
 * status: started
alpinerc:~$ pstree -p | grep "dae("
        |-supervise-daemo(3050)---dae(3051)-+-{dae}(3057)
```

可以看到一切正常，进程树正常。
====================================================

```
alpinerc:~$ doas rc-service dae stop
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/dae stop
 * Stopping dae ...                                                                                               [ ok ]
alpinerc:~$ pstree -p | grep "dae("
        |-supervise-daemo(3050)---dae(3214)-+-{dae}(3215)
```

停止服务，dae没有死，pid换了一个
====================================================

```
alpinerc:~$ doas kill -9 3214
alpinerc:~$ pstree -p | grep "dae("
        |-supervise-daemo(3050)---dae(3230)-+-{dae}(3231)
```

kill掉dae，pid又换了一个
====================================================

```
alpinerc:~$ doas kill -9 3050
alpinerc:~$ doas kill -9 3230
alpinerc:~$ doas rc-service dae start
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/dae start
 * Starting dae ...
 * Detaching to start `/usr/local/bin/dae'
alpinerc:~$ doas rc-service dae stop
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/dae stop
 * Stopping dae ...                                                                                               [ ok ]
alpinerc:~$ pstree -p | grep "dae("
alpinerc:~$
```

把daemon和dae都kill掉，再次start/stop，神奇的事情发生了：dae进程没有了！

### Environment

- **Dae version (use `dae --version`)**: v0.5.1
- **OS (e.g `cat /etc/os-release`)**: Alpine Linux v3.19
- **Kernel (e.g. `uname -a`)**: 6.6.14-0-virt
- **Others**: no

### Anything else?

No.

**Comment by MarksonHon** [comment]
233333，脚本型 init 系统果然都不是很靠谱，你可以修改下服务脚本，不用 supervise-daemon 当进程守护看下

**Comment by eskimokk** [comment]
> 233333，脚本型 init 系统果然都不是很靠谱，你可以修改下服务脚本，不用 supervise-daemon 当进程守护看下

问题是我其他服务没有这个问题啊，比如mosdns

**Comment by MarksonHon** [comment]
@eskimokk 其它服务的脚本呢？
