### ISSUE TITLE
[Bug Report] <pve下WAN口使用vlan时自动配置内核参数路径出现问题>

### ISSUE THREAD

**Issue by shminer** [daeuniverse/dae#463]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

当pve下使用vlan作为wan口(出口网关)时,例如出口网关为vmbr0.123,自动配置内核参数会出现错误:
`bindWan: vmbr0.123: open /proc/sys/net/ipv4/conf/vmbr0/123/accept_local: no such file or directory`
看起来是"."被作为了路径分隔符了,希望作者修复

### Environment

not need

**Comment by jschwinger233** [comment]
pr #458 之后应该就不用设置这个了
