### ISSUE TITLE
[Bug Report] <title>Ubuntu 启动不起来

### ISSUE THREAD

**Issue by xxuun** [daeuniverse/dae#468]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

系统：
root@bms-x9ds:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

内核版本：
root@bms-x9ds:~# uname -r
5.8.0-63-generic

内核选项：
root@bms-x9ds:~# (zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) | grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|NET_EGRESS|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED is not set'
gzip: /proc/config.gz: No such file or directory
cat: /boot/config: No such file or directory
CONFIG_CGROUPS=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

报错：
Mar 05 17:26:06 bms-x9ds systemd[1]: Starting dae Service...
Mar 05 17:26:06 bms-x9ds dae[5455]: level=info msg="Include config files: [/usr/local/etc/dae/config.dae]"
Mar 05 17:26:06 bms-x9ds dae[5455]: level=info msg="Loading eBPF programs and maps into the kernel..."
Mar 05 17:26:06 bms-x9ds dae[5455]: level=info msg="The loading process takes about 120MB free memory, which will be released after loading. Insufficient memory will cause loading failure."
Mar 05 17:26:06 bms-x9ds dae[5455]: time="2024-03-05T17:26:06+08:00" level=fatal msg="load eBPF objects: field TproxyLanIngress: program tproxy_lan_ingress: apply CO-RE relocations: load kernel spec: no BTF >
Mar 05 17:26:06 bms-x9ds systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 17:26:06 bms-x9ds systemd[1]: dae.service: Failed with result 'exit-code'.
Mar 05 17:26:06 bms-x9ds systemd[1]: Failed to start dae Service.

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by wanlce** [comment]
bash xxx.sh 执行下下面的脚本
```bash
#!/bin/bash

# 定义内核配置要求
declare -A config_requirements=(
    [CONFIG_BPF]="y"
    [CONFIG_BPF_SYSCALL]="y"
    [CONFIG_BPF_JIT]="y"
    [CONFIG_CGROUPS]="y"
    [CONFIG_KPROBES]="y"
    [CONFIG_NET_INGRESS]="y"
    [CONFIG_NET_EGRESS]="y"
    [CONFIG_NET_SCH_INGRESS]="m"
    [CONFIG_NET_CLS_BPF]="m"
    [CONFIG_NET_CLS_ACT]="y"
    [CONFIG_BPF_STREAM_PARSER]="y"
    [CONFIG_DEBUG_INFO]="y"
    [CONFIG_DEBUG_INFO_BTF]="y"
    [CONFIG_KPROBE_EVENTS]="y"
    [CONFIG_BPF_EVENTS]="y"
)

# 查找内核配置文件的函数
find_config_file() {
    local paths=(
        "/proc/config.gz"
        "/boot/config-$(uname -r)"
        "/usr/src/linux-$(uname -r)/.config"
        "/usr/src/linux-config-$(uname -r)"
    )
    for path in "${paths[@]}"; do
        if [ -f "$path" ]; then
            echo "$path"
            return
        fi
    done
}

# 检查内核配置的函数
check_config() {
    local config=$1
    local expected_value=$2
    local config_value

    if [[ $config_file == *.gz ]]; then
        config_value=$(zgrep "^$config" "$config_file" || echo "")
    else
        config_value=$(grep "^$config" "$config_file" || echo "")
    fi

    if [[ $config_value =~ $config=$expected_value ]]; then
        return 0
    else
        echo "配置项 $config 需要设置为 $expected_value，当前设置为 ${config_value#*=}"
        return 1
    fi
}

config_file=$(find_config_file)

if [ -z "$config_file" ]; then
    echo "无法找到内核配置文件。"
    exit 1
fi

echo "使用内核配置文件: $config_file"

all_good=true
for config in "${!config_requirements[@]}"; do
    if ! check_config "$config" "${config_requirements[$config]}"; then
        all_good=false
    fi
done

if $all_good; then
    echo -e "\e[1;32m可以吃大鹅了\e[0m"
else
    echo "有些内核配置不符合要求，请根据上述提示进行调整。"
fi

```
Powered by ChatGPT

**Comment by xxuun** [comment]
> bash xxx.sh 执行下下面的脚本
> 
> ```shell
> #!/bin/bash
> 
> # 定义内核配置要求
> declare -A config_requirements=(
>     [CONFIG_BPF]="y"
>     [CONFIG_BPF_SYSCALL]="y"
>     [CONFIG_BPF_JIT]="y"
>     [CONFIG_CGROUPS]="y"
>     [CONFIG_KPROBES]="y"
>     [CONFIG_NET_INGRESS]="y"
>     [CONFIG_NET_EGRESS]="y"
>     [CONFIG_NET_SCH_INGRESS]="m"
>     [CONFIG_NET_CLS_BPF]="m"
>     [CONFIG_NET_CLS_ACT]="y"
>     [CONFIG_BPF_STREAM_PARSER]="y"
>     [CONFIG_DEBUG_INFO]="y"
>     [CONFIG_DEBUG_INFO_BTF]="y"
>     [CONFIG_KPROBE_EVENTS]="y"
>     [CONFIG_BPF_EVENTS]="y"
> )
> 
> # 查找内核配置文件的函数
> find_config_file() {
>     local paths=(
>         "/proc/config.gz"
>         "/boot/config-$(uname -r)"
>         "/usr/src/linux-$(uname -r)/.config"
>         "/usr/src/linux-config-$(uname -r)"
>     )
>     for path in "${paths[@]}"; do
>         if [ -f "$path" ]; then
>             echo "$path"
>             return
>         fi
>     done
> }
> 
> # 检查内核配置的函数
> check_config() {
>     local config=$1
>     local expected_value=$2
>     local config_value
> 
>     if [[ $config_file == *.gz ]]; then
>         config_value=$(zgrep "^$config" "$config_file" || echo "")
>     else
>         config_value=$(grep "^$config" "$config_file" || echo "")
>     fi
> 
>     if [[ $config_value =~ $config=$expected_value ]]; then
>         return 0
>     else
>         echo "配置项 $config 需要设置为 $expected_value，当前设置为 ${config_value#*=}"
>         return 1
>     fi
> }
> 
> config_file=$(find_config_file)
> 
> if [ -z "$config_file" ]; then
>     echo "无法找到内核配置文件。"
>     exit 1
> fi
> 
> echo "使用内核配置文件: $config_file"
> 
> all_good=true
> for config in "${!config_requirements[@]}"; do
>     if ! check_config "$config" "${config_requirements[$config]}"; then
>         all_good=false
>     fi
> done
> 
> if $all_good; then
>     echo -e "\e[1;32m可以吃大鹅了\e[0m"
> else
>     echo "有些内核配置不符合要求，请根据上述提示进行调整。"
> fi
> ```
> 
> Powered by ChatGPT

谢谢反馈，用其他方案解决了，感谢。
