### ISSUE TITLE
[Enhancement] Work with systemd-nspawn

### ISSUE THREAD

**Issue by KiriKira** [daeuniverse/dae#471]
### Improvement Suggestion

Try to run dae in systemd-nspawn container, the following two problems were encountered:
1. rlimit
![image](https://github.com/daeuniverse/dae/assets/32393884/48db4cb4-5d78-4df1-a777-32032a32123a)
dae seems to force rlimit to be reset before running, even if LimitMEMLOCK=infinity has been set in systemd
![image](https://github.com/daeuniverse/dae/assets/32393884/446bd4dd-c357-483b-a781-557d471dcb29)

2. bindmount /sys
I tried to bind mount /sys to nspawn following docker's usage, but this causes nspawn to fail to start (since the cgroup is also in /sys)
 So I tried just mount /sys/fs/bpf, I don't know if that's enough because problem 1 blocked me. If you know what to do, let me know.

### Potential Benefits

Provide a new option for running dae in containers, which will be much more 清真 than docker

**Comment by mzz2017** [comment]
Sorry and this may not be something that dae can solve. These requirements are necessary for dae. Therefore, how to use dae through systemd-nspawn needs everyone to explore. Everyone is welcome to update progress and discuss here.

**Comment by mzz2017** [comment]
It is requiresite for ebpf program. You can remove the related code and compile it and try again.

**Comment by KiriKira** [comment]
Problem resolved by the following nspawn config:

```code
# /etc/systemd/nspawn/ASA.nspawn

[Exec]
PrivateUsers=no
#LimitMEMLOCK=infinity
#LimitNOFILE=infinity
SystemCallFilter=@privileged

[Files]
Bind=/sys/fs/bpf
```

The key point is SystemCallFilter=@privileged and Bind=/sys/fs/bpf, which allow dae to run in nspawn container.

If anyone is interested in more, feel free to read: <https://kirikira.moe/post/49/>
