### ISSUE TITLE
支持hysteria协议

### ISSUE THREAD

**Issue by xtccc** [daeuniverse/dae#48]

**Comment by mzz2017** [comment]
由于 hysteria 参数过多且与客户端的网络有关， dae 不是很倾向于实现它。

幸运的是，据[若干反馈](https://github.com/EAimTY/tuic/issues/161)，tuic v5 通常情况下比 hysteria 效果更好，**dae 已将它实现**。

稍后发布的 v0.2.1rc1 将会带来 tuic 的支持，相关讨论见 <https://github.com/daeuniverse/dae/discussions/182>。

**Comment by xtccc** [comment]
挺好 ，下次发版了我试试。
