### ISSUE TITLE
[Bug Report] dae can't recognize pppoe dial-up interface and use it as wan_interface

### ISSUE THREAD

**Issue by yesiamchinese** [daeuniverse/dae#486]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

1. setup a pppoe dial-up config
2. dail-up to internet, the pppoe interface name is ppp0
3. set dae wan_interface to 'auto' or 'ppp0'
3. start dae
4. access www.baidu.com normally
5. access foreign website fails.

### Expected Behavior

dae shoud using pppoe dial-up interface automaticly.

### Steps to Reproduce

1. dae version v0.5.1
2. Debian 12 and Ubuntu 22.04 without GUI
3. Debian 12 kernel version Linux 6.1.0-18-amd64, Ubuntu 22.04 kernel verison Linux 5.15.0-101-generic

dae config file:

config.dae:
global {
    lan_interface: ens192
    wan_interface: auto # ppp0
    log_level: info # log level：error，warn，info，debug，trace。
    auto_config_kernel_parameter: true
    dial_mode: domain

    # sniffing
    sniffing_timeout: 200ms
    allow_insecure: true

    so_mark_from_dae: 1234

    # tls
    tls_implementation: utls
    utls_imitate: chrome_auto

    ##### connectivty check
    tcp_check_url: 'http://cp.cloudflare.com,1.1.1.1'
    udp_check_dns: 'dns.google.com:53,8.8.8.8'
    check_interval: 30s
    check_tolerance: 50ms
}

# 订阅配置
subscription {
}

# nod
node {
    hysteria:    'socks5://localhost:1080' # hysteria verion 2 client socks5 function normally
}

# group
group {
    dae_proxy {
        policy: min #fixed(0)
    }
}

# dns
dns {
  upstream {
    googledns: 'tcp://dns.google.com:53'
    #alidns: 'udp://dns.alidns.com:53'
    alidns: 'udp://223.5.5.5:53'
  }

  routing {
    request {
      qname(geosite:cn) -> alidns
      fallback: googledns
    }

  response {
      upstream(googledns) -> accept
      ip(geoip:private) && !qname(geosite:cn) -> googledns
      # default accept
      fallback: accept
    }
  }
}

# routing
routing {
    pname(NetworkManager) -> direct
    pname(hysteria) -> direct # hysteria verion 2 process name

    dip(223.5.5.5/32) -> direct
    dip(224.0.0.0/3, 'ff00::/8') -> direct
    dip(geoip:private) -> direct
    
    ## rules
    domain(cp.cloudflare.com) -> direct
    ip(8.8.8.8) -> direct
    ip(1.1.1.1/32) -> direct
    ip(223.5.5.5) -> direct
    ip(geoip:cn) -> direct
    domain(geosite:cn) -> direct
    domain(geosite:category-ads) -> block

    # default proxy
    fallback: dae_proxy
}

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by mzz2017** [comment]
@yesiamchinese 已知问题，pppoe 不支持作为 wan 接口

**Comment by yesiamchinese** [comment]
Will it be solved in later version ?

**Comment by MarksonHon** [comment]
@yesiamchinese nope, PPPoE is a old protocol that should be replaced by iPoE.

**Comment by yesiamchinese** [comment]
The PPPoE protocol is still widely used by several major telecom ISP in mainland China.

**Comment by MarksonHon** [comment]
> The PPPoE protocol is still widely used by several major telecom ISP in mainland China.

Well, but it's hard to use eBPF to proxy wan while wan is a PPPoE interface. Using your upper device (such as ISP's modem) as the PPPoE device will be helpful for you.
