### ISSUE TITLE
level=fatal msg="load eBPF objects: field TproxyWanEgress: program tproxy_wan_egress: load program: invalid argument: ca>

### ISSUE THREAD

**Issue by hiifeng** [daeuniverse/dae#506]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

在玩客云上运行dae失败，请求支持。

### Current Behavior

我为玩客云编译了armbian内核，以支持运行dae。

root@onecloud:~# uname -r

6.7.12-edge-meson

root@onecloud:~# (zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) | grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|NET_EGRESS|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED is not set'

CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_DEBUG_INFO=y
#CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_DEBUG_INFO_BTF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
root@onecloud:~#

目前的内核版本为6.7.12-edge-meson，同时Kernel Configurations满足dae的要求。

尝试启动dae，报如下错误。

root@onecloud:~# systemctl start dae
Job for dae.service failed because the control process exited with error code.
See "systemctl status dae.service" and "journalctl -xeu dae.service" for details.

root@onecloud:~# systemctl status dae.service
× dae.service - dae Service
     Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-04-24 19:38:42 CST; 20s ago
       Docs: https://github.com/daeuniverse/dae
    Process: 1458 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS)
    Process: 1464 ExecStart=/usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae (code=exited, status=1/FAILURE)
   Main PID: 1464 (code=exited, status=1/FAILURE)
        CPU: 38.882s

Apr 24 19:38:03 onecloud dae[1464]: level=info msg="Include config files: [/etc/dae/config.dae]"
Apr 24 19:38:03 onecloud dae[1464]: level=warning msg="No node found."
Apr 24 19:38:03 onecloud dae[1464]: level=warning msg="No interface to bind."
Apr 24 19:38:03 onecloud dae[1464]: level=info msg="Loading eBPF programs and maps into the kernel..."
Apr 24 19:38:03 onecloud dae[1464]: level=info msg="The loading process takes about 120MB free memory, which will be released after loading. Insufficient me>
Apr 24 19:38:42 onecloud dae[1464]: level=fatal msg="load eBPF objects: field TproxyWanEgress: program tproxy_wan_egress: load program: invalid argument: ca>
Apr 24 19:38:42 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Apr 24 19:38:42 onecloud systemd[1]: dae.service: Failed with result 'exit-code'.
Apr 24 19:38:42 onecloud systemd[1]: Failed to start dae Service.
Apr 24 19:38:42 onecloud systemd[1]: dae.service: Consumed 38.882s CPU time.

### Steps to Reproduce

root@onecloud:~# cat /etc/dae/config.dae
global{}
routing{}

root@onecloud:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           980Mi       100Mi       748Mi       4.0Mi       131Mi       852Mi
Swap:          490Mi          0B       490Mi
root@onecloud:~#

### Environment

root@onecloud:~# dae --version
dae version v0.6.0rc2
go runtime go1.22.2 linux/arm
Copyright (c) 2022-2024 @daeuniverse
License GNU AGPLv3 <https://github.com/daeuniverse/dae/blob/main/LICENSE>

root@onecloud:~# cat /etc/os-release
PRETTY_NAME="Armbian-unofficial 24.5.0-trunk jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
PRIVACY_POLICY_URL="https://www.armbian.com"
UBUNTU_CODENAME=jammy
ARMBIAN_PRETTY_NAME="Armbian-unofficial 24.5.0-trunk jammy"

root@onecloud:~# uname -a
Linux onecloud 6.7.12-edge-meson #1 SMP Wed Apr  3 13:11:59 UTC 2024 armv7l armv7l armv7l GNU/Linux

**Comment by mzz2017** [comment]
log level 开 fatal 看看

**Comment by hiifeng** [comment]
> log level 开 fatal 看看

首先感谢您的回复，帮我分析故障原因。谢谢
根据你的提示，我修改了日志级别。

root@onecloud:~# cat /etc/dae/config.dae
global{
log_level: fatal
}
routing{}

再次尝试启动dae

root@onecloud:/etc/dae# systemctl start dae
Job for dae.service failed because the control process exited with error code.
See "systemctl status dae.service" and "journalctl -xeu dae.service" for details                                                                             .
root@onecloud:/etc/dae# systemctl status dae.service
× dae.service - dae Service
     Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-04-25 08:34:07 CST; 54s ago
       Docs: https://github.com/daeuniverse/dae
    Process: 1456 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS)
    Process: 1462 ExecStart=/usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae (code=exited, status=1/FAILURE)
   Main PID: 1462 (code=exited, status=1/FAILURE)
        CPU: 39.131s

Apr 25 08:33:28 onecloud systemd[1]: Starting dae Service...
Apr 25 08:34:07 onecloud dae[1462]: level=fatal msg="callbacks are not allowed in non-JITed programs
Apr 25 08:34:07 onecloud dae[1462]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86"
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Failed with result 'exit-code'.
Apr 25 08:34:07 onecloud systemd[1]: Failed to start dae Service.
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Consumed 39.131s CPU time.

root@onecloud:~# tail -f /var/log/syslog
Apr 25 08:33:28 onecloud systemd[1]: Starting dae Service...
Apr 25 08:33:28 onecloud systemd-udevd[1470]: Using default interface naming scheme 'v249'.
Apr 25 08:33:28 onecloud systemd-udevd[1469]: Using default interface naming scheme 'v249'.
Apr 25 08:33:28 onecloud systemd[1]: run-netns-daens.mount: Deactivated successfully.
Apr 25 08:33:56 onecloud chronyd[1311]: Selected source **** (0.ubuntu.pool.ntp.org)
Apr 25 08:34:07 onecloud dae[1462]: level=fatal msg="callbacks are not allowed in non-JITed programs
Apr 25 08:34:07 onecloud dae[1462]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86"
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Failed with result 'exit-code'.
Apr 25 08:34:07 onecloud systemd[1]: Failed to start dae Service.
Apr 25 08:34:07 onecloud systemd[1]: dae.service: Consumed 39.131s CPU time.
Apr 25 08:35:01 onecloud CRON[1519]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Apr 25 08:35:29 onecloud systemd[1]: Starting Daily man-db regeneration...
Apr 25 08:35:51 onecloud systemd[1]: man-db.service: Deactivated successfully.
Apr 25 08:35:51 onecloud systemd[1]: Finished Daily man-db regeneration.
Apr 25 08:35:51 onecloud systemd[1]: man-db.service: Consumed 1.093s CPU time.
Apr 25 08:40:29 onecloud systemd[1]: Starting system activity accounting tool...
Apr 25 08:40:29 onecloud systemd[1]: sysstat-collect.service: Deactivated successfully.
Apr 25 08:40:29 onecloud systemd[1]: Finished system activity accounting tool.

我发现dae在启动时链接了ntp服务器“Selected source **** (0.ubuntu.pool.ntp.org)”，但是我的本地时间是正确的，猜测可能是dae支持vmess，进行自动校时。
另外有一行这样的提示“level=fatal msg="callbacks are not allowed in non-JITed programs”，我猜测应该是这个原因引起的，但是我不知道non-JITed是什么，请求支持，谢谢

**Comment by jschwinger233** [comment]
@hiifeng 试试 `echo 1 > /proc/sys/net/core/bpf_jit_enable` ?

**Comment by hiifeng** [comment]
> @hiifeng 试试 `echo 1 > /proc/sys/net/core/bpf_jit_enable` ?

root@onecloud:~# echo 1 > /proc/sys/net/core/bpf_jit_enable

root@onecloud:~# cat /proc/sys/net/core/bpf_jit_enable
1

root@onecloud:~# systemctl start dae
Job for dae.service failed because the control process exited with error code.
See "systemctl status dae.service" and "journalctl -xeu dae.service" for details                                                                             .

root@onecloud:~# systemctl status dae.service
× dae.service - dae Service
     Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-04-25 09:47:48 CST; 1min 27s ago
       Docs: https://github.com/daeuniverse/dae
    Process: 7282 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS)
    Process: 7288 ExecStart=/usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae (code=exited, status=1/FAILURE)
   Main PID: 7288 (code=exited, status=1/FAILURE)
        CPU: 39.614s

Apr 25 09:47:08 onecloud systemd[1]: Starting dae Service...
Apr 25 09:47:48 onecloud dae[7288]: level=fatal msg="JIT doesn't support bpf-to-bpf calls
Apr 25 09:47:48 onecloud dae[7288]: callbacks are not allowed in non-JITed programs
Apr 25 09:47:48 onecloud dae[7288]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86"
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Failed with result 'exit-code'.
Apr 25 09:47:48 onecloud systemd[1]: Failed to start dae Service.
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Consumed 39.614s CPU time.
root@onecloud:~#


root@onecloud:~# tail -f /var/log/syslog
Apr 25 09:47:08 onecloud systemd[1]: Starting dae Service...
Apr 25 09:47:09 onecloud systemd-udevd[7295]: Using default interface naming scheme 'v249'.
Apr 25 09:47:09 onecloud systemd[1]: run-netns-daens.mount: Deactivated successfully.
Apr 25 09:47:09 onecloud systemd-udevd[7296]: Using default interface naming scheme 'v249'.
Apr 25 09:47:48 onecloud dae[7288]: level=fatal msg="JIT doesn't support bpf-to-bpf calls
Apr 25 09:47:48 onecloud dae[7288]: callbacks are not allowed in non-JITed programs
Apr 25 09:47:48 onecloud dae[7288]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86"
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Failed with result 'exit-code'.
Apr 25 09:47:48 onecloud systemd[1]: Failed to start dae Service.
Apr 25 09:47:48 onecloud systemd[1]: dae.service: Consumed 39.614s CPU time.

这次提示了“JIT doesn't support bpf-to-bpf calls”。

**Comment by jschwinger233** [comment]
arm bpf 的问题。。。  bpf 内核测试 CI 看来要加上 arm 虚拟机

**Comment by mzz2017** [comment]
你或许可以使用0.5.1正式版，或者0.6.0rc1

**Comment by hiifeng** [comment]
> 你或许可以使用0.5.1正式版，或者0.6.0rc1

使用0.5.1正式版启动起来了。
root@onecloud:~/dae# systemctl status dae
● dae.service - dae Service
     Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-04-25 10:06:55 CST; 16s ago
       Docs: https://github.com/daeuniverse/dae
    Process: 7408 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS)
   Main PID: 7413 (dae)
      Tasks: 9 (limit: 2164)
     Memory: 30.9M
        CPU: 28.605s
     CGroup: /system.slice/dae.service
             └─7413 /usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae

Apr 25 10:06:27 onecloud systemd[1]: Starting dae Service...
Apr 25 10:06:55 onecloud systemd[1]: Started dae Service.

非常感谢作者的回复。接下来我会尝试给N1适配dae可以使用的内核，提交到https://github.com/daeuniverse/armbian-btf-kernel/releases，方便更多人的使用。

**Comment by mzz2017** [comment]
@hiifeng 感谢，你愿意维护这个仓库吗，这个仓库已经失修了

**Comment by mzz2017** [comment]
@jschwinger233 这个问题目前有解吗

**Comment by hiifeng** [comment]
> @hiifeng 感谢，你愿意维护这个仓库吗，这个仓库已经失修了

我很乐意维护，不过我水平有限，不懂的今后还要请教您。

**Comment by jschwinger233** [comment]
> @jschwinger233 这个问题目前有解吗

不确定，可能要改内核才能彻底支持，但也有可能通过修改我们的bpf程序来绕过。思路是不用（或简化）bpf2bpf，改用兼容性更好的tailcall。

**Comment by mzz2017** [comment]
@hiifeng 没问题，保持沟通

**Comment by mzz2017** [comment]
@jschwinger233 bpf2bpf是什么，我怀疑是 bpf_timer 的回调函数的问题？

**Comment by mzz2017** [comment]
@jschwinger233 原来如此，学习了

**Comment by zhb236623zhb** [comment]
> > 你或许可以使用0.5.1正式版，或者0.6.0rc1
> 
> 使用0.5.1正式版启动起来了。 root@onecloud:~/dae# systemctl status dae ● dae.service - dae Service Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled) Active: active (running) since Thu 2024-04-25 10:06:55 CST; 16s ago Docs: https://github.com/daeuniverse/dae Process: 7408 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS) Main PID: 7413 (dae) Tasks: 9 (limit: 2164) Memory: 30.9M CPU: 28.605s CGroup: /system.slice/dae.service └─7413 /usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae
> 
> Apr 25 10:06:27 onecloud systemd[1]: Starting dae Service... Apr 25 10:06:55 onecloud systemd[1]: Started dae Service.
> 
> 非常感谢作者的回复。接下来我会尝试给N1适配dae可以使用的内核，提交到[https://github.com/daeuniverse/armbian-btf-kernel/releases，方便更多人的使用。](https://github.com/daeuniverse/armbian-btf-kernel/releases%EF%BC%8C%E6%96%B9%E4%BE%BF%E6%9B%B4%E5%A4%9A%E4%BA%BA%E7%9A%84%E4%BD%BF%E7%94%A8%E3%80%82)
 我的玩客云用了0.5.1 还是启动不起来。能否出一期教程，从使用哪个ARMBIAN版本开始。

**Comment by hiifeng** [comment]
> > > 你或许可以使用0.5.1正式版，或者0.6.0rc1
> > 
> > 
> > 使用0.5.1正式版启动起来了。 root@onecloud:~/dae# systemctl status dae ● dae.service - dae Service Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled) Active: active (running) since Thu 2024-04-25 10:06:55 CST; 16s ago Docs: https://github.com/daeuniverse/dae Process: 7408 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS) Main PID: 7413 (dae) Tasks: 9 (limit: 2164) Memory: 30.9M CPU: 28.605s CGroup: /system.slice/dae.service └─7413 /usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae
> > Apr 25 10:06:27 onecloud systemd[1]: Starting dae Service... Apr 25 10:06:55 onecloud systemd[1]: Started dae Service.
> > 非常感谢作者的回复。接下来我会尝试给N1适配dae可以使用的内核，提交到[https://github.com/daeuniverse/armbian-btf-kernel/releases，方便更多人的使用。](https://github.com/daeuniverse/armbian-btf-kernel/releases%EF%BC%8C%E6%96%B9%E4%BE%BF%E6%9B%B4%E5%A4%9A%E4%BA%BA%E7%9A%84%E4%BD%BF%E7%94%A8%E3%80%82)
> > 我的玩客云用了0.5.1 还是启动不起来。能否出一期教程，从使用哪个ARMBIAN版本开始。

我最近工作上有点忙，在外地出差。我抽空更新一下博客。

**Comment by zhb236623zhb** [comment]
> > > > 你或许可以使用0.5.1正式版，或者0.6.0rc1
> > > 
> > > 
> > > 使用0.5.1正式版启动起来了。 root@onecloud:~/dae# systemctl status dae ● dae.service - dae Service Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled) Active: active (running) since Thu 2024-04-25 10:06:55 CST; 16s ago Docs: https://github.com/daeuniverse/dae Process: 7408 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS) Main PID: 7413 (dae) Tasks: 9 (limit: 2164) Memory: 30.9M CPU: 28.605s CGroup: /system.slice/dae.service └─7413 /usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae
> > > Apr 25 10:06:27 onecloud systemd[1]: Starting dae Service... Apr 25 10:06:55 onecloud systemd[1]: Started dae Service.
> > > 非常感谢作者的回复。接下来我会尝试给N1适配dae可以使用的内核，提交到[https://github.com/daeuniverse/armbian-btf-kernel/releases，方便更多人的使用。](https://github.com/daeuniverse/armbian-btf-kernel/releases%EF%BC%8C%E6%96%B9%E4%BE%BF%E6%9B%B4%E5%A4%9A%E4%BA%BA%E7%9A%84%E4%BD%BF%E7%94%A8%E3%80%82)
> > > 我的玩客云用了0.5.1 还是启动不起来。能否出一期教程，从使用哪个ARMBIAN版本开始。
> 
> 我最近工作上有点忙，在外地出差。我抽空更新一下博客。

试了好多个版本的ARMBIAN 也试了 0.5.1 ，v0.6.0rc1，v0.6.0rc2 都 是一样启动不起来。期待您的更新。

**Comment by FreeJ233** [comment]
> > @hiifeng 试试 `echo 1 > /proc/sys/net/core/bpf_jit_enable` ?
> 
> root@onecloud:~# echo 1 > /proc/sys/net/core/bpf_jit_enable
> 
> root@onecloud:~# cat /proc/sys/net/core/bpf_jit_enable 1
> 
> root@onecloud:~# systemctl start dae Job for dae.service failed because the control process exited with error code. See "systemctl status dae.service" and "journalctl -xeu dae.service" for details .
> 
> root@onecloud:~# systemctl status dae.service × dae.service - dae Service Loaded: loaded (/etc/systemd/system/dae.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Thu 2024-04-25 09:47:48 CST; 1min 27s ago Docs: https://github.com/daeuniverse/dae Process: 7282 ExecStartPre=/usr/bin/dae validate -c /etc/dae/config.dae (code=exited, status=0/SUCCESS) Process: 7288 ExecStart=/usr/bin/dae run --disable-timestamp -c /etc/dae/config.dae (code=exited, status=1/FAILURE) Main PID: 7288 (code=exited, status=1/FAILURE) CPU: 39.614s
> 
> Apr 25 09:47:08 onecloud systemd[1]: Starting dae Service... Apr 25 09:47:48 onecloud dae[7288]: level=fatal msg="JIT doesn't support bpf-to-bpf calls Apr 25 09:47:48 onecloud dae[7288]: callbacks are not allowed in non-JITed programs Apr 25 09:47:48 onecloud dae[7288]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86" Apr 25 09:47:48 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE Apr 25 09:47:48 onecloud systemd[1]: dae.service: Failed with result 'exit-code'. Apr 25 09:47:48 onecloud systemd[1]: Failed to start dae Service. Apr 25 09:47:48 onecloud systemd[1]: dae.service: Consumed 39.614s CPU time. root@onecloud:~#
> 
> root@onecloud:~# tail -f /var/log/syslog Apr 25 09:47:08 onecloud systemd[1]: Starting dae Service... Apr 25 09:47:09 onecloud systemd-udevd[7295]: Using default interface naming scheme 'v249'. Apr 25 09:47:09 onecloud systemd[1]: run-netns-daens.mount: Deactivated successfully. Apr 25 09:47:09 onecloud systemd-udevd[7296]: Using default interface naming scheme 'v249'. Apr 25 09:47:48 onecloud dae[7288]: level=fatal msg="JIT doesn't support bpf-to-bpf calls Apr 25 09:47:48 onecloud dae[7288]: callbacks are not allowed in non-JITed programs Apr 25 09:47:48 onecloud dae[7288]: processed 229682 insns (limit 1000000) max_states_per_insn 68 total_states 10138 peak_states 1360 mark_read 86" Apr 25 09:47:48 onecloud systemd[1]: dae.service: Main process exited, code=exited, status=1/FAILURE Apr 25 09:47:48 onecloud systemd[1]: dae.service: Failed with result 'exit-code'. Apr 25 09:47:48 onecloud systemd[1]: Failed to start dae Service. Apr 25 09:47:48 onecloud systemd[1]: dae.service: Consumed 39.614s CPU time.
> 
> 这次提示了“JIT doesn't support bpf-to-bpf calls”。这一项也是y：CONFIG_BPF_JIT=y

大佬，我编译随身wifi的内核后遇同样的JIT doesn't support bpf-to-bpf calls问题，请问你是怎么解决的？

**Comment by mzz2017** [comment]
@FreeJ233 降级到0.5.1

**Comment by FreeJ233** [comment]
> @FreeJ233 降级 dae 到 0.5.1，armv5/v6/v7 的 bpf 支持有点局限

感谢大佬回复，随身wifi棒子是高通8916，arm64架构的，内核编译的选项也和要求的一样，问题和 @hiifeng 大佬的一样，所以问问怎么解决

**Comment by jschwinger233** [comment]
@FreeJ233 你 `cat /proc/sys/net/core/bpf_jit_enable` 的结果是什么，如果是 1 的话 `echo 0 > /proc/sys/net/core/bpf_jit_enable` 再试试 0.5.1？

**Comment by FreeJ233** [comment]
> @FreeJ233 你 `cat /proc/sys/net/core/bpf_jit_enable` 的结果是什么，如果是 1 的话 `echo 0 > /proc/sys/net/core/bpf_jit_enable` 再试试 0.5.1？

谢谢大佬回复，cat /proc/sys/net/core/bpf_jit_enable结果是1，因为之前看了你的留言，之前编译时特意设置了！

暂时不试0.5.1了，不然以后更新还是用不了，想折腾一下

我的是debian11,内核是5.15，参照你之前的思路我搜索了一下，arm64的6.0以上的内核，有supports mixing bpf2bpf and tailcalls，我研究一下看看能不能解决

**Comment by FreeJ233** [comment]
JIT doesn't support bpf-to-bpf calls 问题已经解决，Dae和Daed都能正常使用，wifi棒子吃鹅成功。 @jschwinger233 大佬你的思路是对的，牛逼。

产生问题的原因 Hou Tao <houtao1@huawei.com>在修复linux内核提到过：
The root cause is the size of BPF_PSEUDO_FUNC instruction increases
from 2 to 3 after the address of called bpf-function is settled and
there are two bpf-to-bpf calls in test_pkt_access. The generated
instructions are shown below:

>before callback_fn is jited, its addr is 0x1-00000001
0x48:  21 00 C0 D2    movz x1, #0x1, lsl #32
0x4c:  21 00 80 F2    movk x1, #0x1

>after callback_fn is jited, its addr is 0xfffffe0017f2fb84
0x48:  E1 3F C0 92    movn x1, #0x1ff, lsl #32
0x4c:  41 FE A2 F2    movk x1, #0x17f2, lsl #16
0x50:  81 70 9F F2    movk x1, #0xfb84

解决方法，需要更改arch/arm64/net/bpf_jit_comp.c再重新编译，

--- a/arch/arm64/net/bpf_jit_comp.c
+++ b/arch/arm64/net/bpf_jit_comp.c
@@ -792,7 +792,10 @@ static int build_insn(const struct bpf_insn *insn, struct jit_ctx *ctx,
 		u64 imm64;
 
 		imm64 = (u64)insn1.imm << 32 | (u32)imm;
-		emit_a64_mov_i64(dst, imm64, ctx);
+		if (bpf_pseudo_func(insn))
+			emit_addr_mov_i64(dst, imm64, ctx);
+		else
+			emit_a64_mov_i64(dst, imm64, ctx);
 
 		return 1;
 	}

编译前需要注意两点
1. CONFIG_BPF_JIT_DEFAULT_ON=y
2. 需要添加include/linux/bpf.h中bpf_pseudo_func的函数声明并将该声明在kernel/bpf/verifier.c中移除。
    具体可以参考我仓库https://github.com/FreeJ233/linux

以上适用与linux 5.15内核。

**Comment by shaneZhang** [comment]
同为玩客云，同样的错误。不知道有没有大神协助修复下该问题。
尝试了0.5.1版本 0.7版本均不行。

**Comment by hiifeng** [comment]
> 同为玩客云，同样的错误。不知道有没有大神协助修复下该问题。
> 
> 尝试了0.5.1版本 0.7版本均不行。
> 
> 
用这个固件
https://www.hicairo.com/post/76.html

**Comment by shaneZhang** [comment]
> > 同为玩客云，同样的错误。不知道有没有大神协助修复下该问题。
> > 尝试了0.5.1版本 0.7版本均不行。
> 
> 用这个固件 https://www.hicairo.com/post/76.html

多谢， 我试试你这个固件，我也自己编辑了下固件，升级到Ubuntu 24.04了，应该是同样的脚本，https://github.com/shaneZhang/armbian-onecloud

**Comment by shaneZhang** [comment]
使用我自己编译的固件也可以启动v0.5.1版本了，但是内核要求使用6.6.43, 6.10.x内核暂时不可以启动，先凑合用吧，有需要的可以自行下载https://github.com/shaneZhang/armbian-onecloud

**Comment by FreeJ233** [comment]
> > 同为玩客云，同样的错误。不知道有没有大神协助修复下该问题。
> > 尝试了0.5.1版本 0.7版本均不行。
> 
> 用这个固件 https://www.hicairo.com/post/76.html

0.5.1之后的版本你编译的固件可以用么？我自己编译出来的不能用，大概知道问题出在哪里，但是不会解决

在这个位置的返回值有问题，arm64的被大神修复了，32位的没人管，我也不会
在这个内核文件下arch/arm/net/bpf_jit_32.c

	/* dst = imm64 */
	case BPF_LD | BPF_IMM | BPF_DW:
	{
		u64 val = (u32)imm | (u64)insn[1].imm << 32;

		emit_a32_mov_i64(dst, val, ctx);

		return 1;
	}

**Comment by shaneZhang** [comment]
> > > 同为玩客云，同样的错误。不知道有没有大神协助修复下该问题。
> > > 尝试了0.5.1版本 0.7版本均不行。
> > 
> > 
> > 用这个固件 https://www.hicairo.com/post/76.html
> 
> 0.5.1之后的版本你编译的固件可以用么？我自己编译出来的不能用，大概知道问题出在哪里，但是不会解决
> 
> 在这个位置的返回值有问题，arm64的被大神修复了，32位的没人管，我也不会 在这个内核文件下arch/arm/net/bpf_jit_32.c
> 
> ```
> /* dst = imm64 */
> case BPF_LD | BPF_IMM | BPF_DW:
> {
> 	u64 val = (u32)imm | (u64)insn[1].imm << 32;
> 
> 	emit_a32_mov_i64(dst, val, ctx);
> 
> 	return 1;
> }
> ```

哈哈，我折腾了半天放弃使用DAE了，改回原装XRAY做透明代理网关，方案都差不多，此路不通就换条路呗
