### ISSUE TITLE
DAE 启动后hiddify无法连接

### ISSUE THREAD

**Issue by coci713** [daeuniverse/dae#516]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [ ] Is it your first time sumbitting an issue

### Current Behavior

已经在config.dae 里的pname(hiddify) -> direct但是如果先启动dae,hiddify便无法连接，但是可以先连接hiddify之后，启动dae就可以

### Steps to Reproduce

1.启动dae,2打开hiddify，3连接hiddify,一直处于连接中

### Environment

- **Dae version (use `dae --version`)**: 0.5.1
- **OS (e.g `cat /etc/os-release`)**:gentoo
- **Kernel (e.g. `uname -a`)**:6.8.4
- **Others**:

**Comment by MarksonHon** [comment]
Running more than one proxy tool which provides transparent proxy is not suggested and supported, and if you use local socks port of other tools to proxy your Internet, set it must_direct.
