### ISSUE TITLE
load eBPF objects: field TproxyLanIngress: program tproxy_lan_ingress

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#52]
The latest commit "[fix: should update system DNS every 5 seconds" caused the error

INFO The loading process takes about 150MB free memory, which will be released after loading. Insufficient memory will cause loading failure.
FATA[0004] load eBPF objects: field TproxyLanIngress: program tproxy_lan_ingress : load program: argument list too long: ; if (match_set->outbound != OUTBOUND_LOGICAL_OR) {: 938: (15) if r2 == 0xfe goto pc-117   ; frame1: R (truncated, 954 line(s) omitted)

Build command
git clone --depth 1 https://github.com/daeuniverse/dae.git
cd dae
git submodule update --init
go mod download
go mod vendor
make CGO_ENABLED=0 GOFLAGS="-trimpath -modcacherw" CFLAGS="-D__REMOVE_BPF_PRINTK" CC=clang goos=linux goarch=amd64 goamd64=v2

Do you have any suggestions?

**Comment by mzz2017** [comment]
@BOBINIUNIU I'll look into it. Could you please try https://github.com/daeuniverse/dae/commit/648710a40e4909ffe29e917265db0d808081dea3 ？ I think this is the problem commit.

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU I'll look into it. Could you please try [648710a](https://github.com/daeuniverse/dae/commit/648710a40e4909ffe29e917265db0d808081dea3) ？ I think this is the problem commit.
I have tested again. You are right, the issue caused by commits 648710a 'feat: add virtual must_rules outbound'

**Comment by mzz2017** [comment]
This problem should be fixed. Could you please try the latest commit?

**Comment by BOBINIUNIU** [comment]
work like a charm!
