### ISSUE TITLE
[Enhancement] Add Golang diagnose support

### ISSUE THREAD

**Issue by jschwinger233** [daeuniverse/dae#523]
### Improvement Suggestion

We noticed community feedback that dae may cause high memory usage. Let's add Golang diagnose support for dae.

It could be either adding `--pprof` command line argument to enable pprof, or integrating with https://github.com/google/gops into dae.

### Potential Benefits

Only with these support we can tell if there is memory leak / goroutine leak.

**Comment by mzz2017** [comment]
Closed by #532
