### ISSUE TITLE
[Support Request] <node> 自定义节点的 ss://LINK  和 vmess://LINK 写法问题

### ISSUE THREAD

**Issue by wmjlxl** [daeuniverse/dae#538]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

大佬们，我 google 了很久很久，就在 issues 里看到过 vless 的写法如下：

HK: 'vless://22e694e4-093d-44bb-8ed2-b0e548c87a2e@idev.example.com:443?type=ws&security=tls&host=idev.example.com&path=%2Fvideo'

但是我却找不到 ss://LINK 和  vmess://LINK 的具体写法，请问有详细例子来参考么？

例如我平时用的 clash 用到的 ss 和  vmess 写法如下，请问如何转换成 dae 能用的  ss://LINK  和 vmess://LINK ?

SS:
- { name: jp, server: jp.sample.com, port: 3333, type: ss, cipher: rc4-md5, password: abcde}

vmess:
- { name: 'us', type: vmess, server: us.sample.com, port: 4444, uuid: 22e694e4-093d-44bb-8ed2-b0e548c87a2e, alterId: 0, cipher: auto, udp: false, network: ws, ws-opts: {path: "/book", headers: {Host: kkk.aaa.bbb.com} } }

### Current Behavior

ss 和 vmess 的具体写法不知

### Steps to Reproduce

请教 ss 和 vmess 的具体写法

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by wanlce** [comment]
@wmjlxl 有个办法，可以用 daed / v2raya 等工具手动填写节点信息后复制链接信息 (

**Comment by wmjlxl** [comment]
thanks @wanlce and @douglarek 

my problem solved.
