### ISSUE TITLE
[Bug Report] hy2 does not support sing-box as a backend

### ISSUE THREAD

**Issue by douglarek** [daeuniverse/dae#552]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [ ] Is it your first time sumbitting an issue

### Current Behavior

sing-box server:

```
    {
      "type": "hysteria2",
      "listen": "::",
      "listen_port": 443,
      "users": [{
        "password": "bar"
      }],
      "tls": {
        "enabled": true,
        "server_name": "a.b.xyz",
        "acme": {
          "domain": "a.b.xyz",
          "email": "i@examle.com"
        }
      }
    }
```

dae config:

```
a: 'hy2://bar@a.b.xyz:443'
```

dae log:

```
level=warning msg="handleConn: failed to dial xxxx:80: connect error: CRYPTO_ERROR 0x178 (remote): tls: no application protocol"
```

If use the original server-side program of hy2, there will be no problem.

### Expected Behavior

...

### Steps to Reproduce

...

### Environment

- **Dae version (use `dae --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by xmapst** [comment]
尝试使用hy2原版的客户端程序连接试试
