### ISSUE TITLE
hy2的node该怎么写？

### ISSUE THREAD

**Issue by jjqtony** [daeuniverse/dae#554]
0.7版本支持hy2了，但我找遍了文档，没找到hy2的节点该怎么写。看到一个是这么写的，a: 'hy2://bar@a.b.xyz:443'  不够吧

**Comment by xmapst** [comment]
> 0.7版本支持hy2了，但我找遍了文档，没找到hy2的节点该怎么写。看到一个是这么写的，a: 'hy2://[bar@a.b.xyz](mailto:bar@a.b.xyz):443' 不够吧

`Actions` 里面拿的 `PR Build` (Preview)版本 然后配置 hysteria2://[auth@]hostname[:port]/?[key=value]&[key=value]...

如是用户密码 则用hysteria2://[auth:password@]hostname[:port]/?[key=value]&[key=value]...

**Comment by jjqtony** [comment]
> > 0.7版本支持hy2了，但我找遍了文档，没找到hy2的节点该怎么写。看到一个是这么写的，a: 'hy2://[bar@a.b.xyz](mailto:bar@a.b.xyz):443' 不够吧
> 
> `Actions` 里面拿的 `PR Build` (Preview)版本 然后配置 hysteria2://[auth@]hostname[:port]/?[key=value]&[key=value]...
> 
> 如是用户密码 则用hysteria2://[auth:password@]hostname[:port]/?[key=value]&[key=value]...

Thanks a lot!

**Comment by mzz2017** [comment]
Fixed in #558
