### ISSUE TITLE
[Support Request] xtls-rprx-vision 目前是不支持的吗？

### ISSUE THREAD

**Issue by shanghaojia-1** [daeuniverse/dae#571]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

xtls-rprx-vision 目前是不支持的吗？我试了下好像没有成功。

### Current Behavior

支持xtls-rprx-vision

### Steps to Reproduce

使用singbox搭建vless xtls-rprx-vision 流控 tls 协议

### Environment

- **v0.6.0 (use `dae --version`)**:
- **debian 12.6 (e.g `cat /etc/os-release`)**:
- **Linux *** 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux**:

**Comment by shanghaojia-1** [comment]
> https://github.com/daeuniverse/dae/blob/main/docs/zh/proxy-protocols.md

我安装了daed，我看daed的web界面是有这个选项的，但是好像不通，有点困惑

**Comment by iopq** [comment]
I had the same issue, doesn't connect to my node (reality/vision) when other UIs do

**Comment by iopq** [comment]
> I had the same issue, doesn't connect to my node (reality/vision) when other UIs do

it's actually mostly working, but when it tries to look up DNS it gets:

Nov 09 18:41:11 desktop daed[2132]: time="Nov 09 18:41:11" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
