### ISSUE TITLE
全部默认，使用windterm 无法ssh连接到自己的服务器为什么？

### ISSUE THREAD

**Issue by slociv** [daeuniverse/dae#574]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

archlinux ，daed run 默认 导入订阅，之后无法使用ssh 连接我的服务器

### Steps to Reproduce

archlinux ，daed run 默认 导入订阅，之后无法使用ssh 连接我的服务器

### Environment

- **Dae version (use `dae --version`)**:最新
- **OS (e.g `cat /etc/os-release`)**:archlinux
- **Kernel (e.g. `uname -a`)**:最新
- **Others**:

### Anything else?

关闭dae 和daed 的命令是什么

**Comment by MarksonHon** [comment]
If you are not good at Linux, use Clash-Meta instead.
