### ISSUE TITLE
[Support Request] openwrt 下启用 dae 后，设备获取到的所有的 dns 的 ttl 都为 0 是正常的吗？

### ISSUE THREAD

**Issue by mrzhiin** [daeuniverse/dae#575]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

openwrt 下启用 dae 后，设备获取到的所有的 dns 的 ttl 都为 0 是正常的吗？

### Current Behavior

局域网设备向网关查询到的所有 dns ttl 为 0

### Expected Behavior

ttl 为实际缓存时长

### Steps to Reproduce

```
dns {
    upstream {
        alidns: 'udp://dns.alidns.com:53'
        googledns: 'tcp+udp://dns.google.com:53'
        local: 'udp://127.0.0.1:53'
    }
    routing {
        request {
            fallback: local
        }
    }
}
```

启用 dae ，在设备上查询 dns

```
doggo www.qq.com "@192.168.4.1"
```

响应

```
www.qq.com.                     CNAME   IN      0s      www.qq.com.eo.dnse2.com.        192.168.4.1:53
www.qq.com.eo.dnse2.com.        A       IN      0s      43.159.107.192                  192.168.4.1:53
```

### Environment

dae version 0.6.0
go runtime go1.21.11 linux/arm64
Copyright (c) 2022-2024 @daeuniverse
License GNU AGPLv3 <https://github.com/daeuniverse/dae/blob/main/LICENSE>

ImmortalWrt 23.05.2

Linux R4S 5.15.150

**Comment by st0nie** [comment]
正常的，domain模式下需要保证每次dns请求都经过dae分流，dae本身就是有dns cache的

**Comment by ppdragon16** [comment]
https://github.com/daeuniverse/dae/issues/858
