### ISSUE TITLE
[Support Request] 如何让 docker0 这个虚拟网卡的流量经过 dae

### ISSUE THREAD

**Issue by linocz1** [daeuniverse/dae#579]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

docker 容器 默认的网络 是不经过 dae 的虚拟网卡的，因为宿主机配置了代理，容器流量没有经过dae 的虚拟网卡 ，所以需要额外的配置，请问有什么快捷的方法 类似与 VMWare Workstation 的 Nat 模式一样吗？

### Current Behavior

docker 容器里面的流量没有经过dae 代理

### Expected Behavior

docker 里面的容器流量都经过 dae 处理转发

### Steps to Reproduce

配置好 dae 的透明代理之后 ，安装 docker，docker 里面启动容器，容器没有 走 dae 代理

### Environment

- **Dae version (use `dae --version`)**: v0.7.0
- **OS (e.g `cat /etc/os-release`)**: ubuntu 24.04
- **Kernel (e.g. `uname -a`)**: 6.8
- **Others**:

**Comment by MarksonHon** [comment]
@linocz1 You are lying. The documentation explains how to proxy docker. Since you raised this issue, it means you didn't read the documentation at all.
