### ISSUE TITLE
[Bug Report] v0.8.0rc1进程消失

### ISSUE THREAD

**Issue by Karmylr** [daeuniverse/dae#586]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [ ] Is it your first time sumbitting an issue

### Current Behavior

启动dae v0.8.0rc1后一段时间进程就会消失，而且ssh会短暂地无法连接，如果ssh已经连接就会显示`client_loop: send disconnect: Connection reset`。v0.7.0没问题

### Expected Behavior

正常运行

### Steps to Reproduce

1. 使用dae v0.8.0rc1
2. `dae run --config /etc/dae/config.dae`

### Environment

- **Dae version**: v0.8.0rc1
- **OS**: OpenWrt SNAPSHOT r26958-9d8d0509bf
- **Kernel**: Linux OpenWrt 6.6.40 #0 SMP Wed Jul 17 21:27:50 2024 x86_64 GNU/Linux

**Comment by mzz2017** [comment]
@Karmylr 进程消失是什么意思？

**Comment by Karmylr** [comment]
@mzz2017 找不到dae进程，也没有崩溃日志

**Comment by mzz2017** [comment]
@Karmylr 贴一下日志

**Comment by Karmylr** [comment]
![图片](https://github.com/user-attachments/assets/adf44084-e78e-474f-b3cb-b677fa98d12c)

**Comment by Karmylr** [comment]
我试过用`nohup dae run -c /etc/dae/config.dae &`，但是复现后日志只有刚启动时的那几条
我还试过直接用ssh执行`dae run -c /etc/dae/config.dae`，每等出现异常日志，ssh就卡住了，按一下回车就显示`client_loop: send disconnect: Connection reset`并断开了

**Comment by embeddedlove** [comment]
试了，有问题，一会儿快一会儿慢的
