### ISSUE TITLE
[Enhancement] 当代理组一段时间无可用节点时关闭icmp

### ISSUE THREAD

**Issue by troubadour-hell** [daeuniverse/dae#592]
### Improvement Suggestion

当代理组一段时间无可用节点时关闭icmp，将该功能作为配置可选项进行实现

### Potential Benefits

将dae所在机器设为opnsense的网关，并通过浮动路由将dns请求转发到dae，希望opnsense能够根据dae代理是否畅通，进而对浮动路由进行启用禁用，即无法通过代理正常请求dns时，opnsense不再将dns转发给dae处理。这可以通过网关监测功能实现，如果网关不通，相关的浮动路由会被自动禁用，网关恢复后，又会被启用。而网关监测是通过icmp实现的，因此能够通过关闭启用icmp响应，对opnsense产生通告作用。已经进行了一个[初步的实现](https://github.com/bradfordzhang/icmp_hijacker)，能否将该功能整合进dae。

**Comment by mzz2017** [comment]
作为周边是很好的，加在 core 里可能不太合适
