### ISSUE TITLE
[Feature Request]  MPTCP 支持

### ISSUE THREAD

**Issue by BakaMai** [daeuniverse/dae#595]
### Feature Request

各位大佬好 .
希望能增加 MPTCP 功能 , 已进内核 , 希望给Shadowsocks 和 V2RAY 之类的协议出站单独开启MPTCP .

### Use Cases

用于 LTE/5G/Starlink/VDSL 等线路聚合  . 目前ClashMeta , Xray-Core , Sing-box 已支持开启这个功能 .
用户仅需自行配置路由即可 .

### Potential Benefits

MPTCP是目前最佳的多线负载均衡以及网络备份方式 .

**Comment by mzz2017** [comment]
来自 kimi:

如果你只有一个物理网络接口（例如eth0），那么使用MPTCP（多路径TCP）可能不会带来直接的好处，因为MPTCP的主要优势在于能够利用多个网络接口或路径来提高带宽、增加冗余和优化网络性能。以下是一些考虑因素：

1. **带宽提升**：由于只有一个接口，MPTCP无法通过多个物理路径来增加带宽。

2. **冗余**：如果这个接口出现故障，MPTCP无法提供备用路径，因为它需要至少两个可用的网络接口。

3. **负载均衡**：在单个接口的情况下，负载均衡不是MPTCP的用例。

4. **网络稳定性**：如果网络连接不稳定，MPTCP无法通过切换到其他路径来提高稳定性，因为它只有一个路径可用。

5. **延迟优化**：由于只有一个路径，MPTCP无法选择更低延迟的路径。

然而，如果你的网络环境或应用程序有以下情况，即使只有一个接口，MPTCP也可能有一定的应用场景：

- **虚拟接口**：如果你的系统中有虚拟接口，比如通过VPN或虚拟网络技术创建的接口，MPTCP可能能够利用这些虚拟接口来实现多路径传输。

- **链路聚合**：如果你的网络设备支持链路聚合（如LACP），可以将多个物理接口捆绑成一个逻辑接口，MPTCP可以在这个逻辑接口上实现多路径传输。

- **将来的扩展**：如果你计划将来增加更多的网络接口，现在启用MPTCP可以为将来的扩展做好准备。

- **特定应用场景**：某些特定的应用或服务可能需要MPTCP的特性，即使在单个接口上，也可能通过软件层面的模拟来实现MPTCP的部分功能。

总的来说，如果你只有一个物理网络接口，MPTCP可能不会带来显著的性能提升。但是，根据你的具体需求和网络环境，评估MPTCP的潜在好处和适用性仍然是值得考虑的。

**Comment by mzz2017** [comment]
多个接口（多个ip）的情况下确实还是能有提升的

**Comment by BakaMai** [comment]
Oh my God , 没想到那么快就支持了 , 非常感谢两位dev .
