### ISSUE TITLE
请求支持Reality协议

### ISSUE THREAD

**Issue by ray154856235** [daeuniverse/dae#606]
### Improvement Suggestion

请求支持Reality协议

### Potential Benefits

Reality协议是目前最安全的协议,希望能支持

**Comment by cubercsl** [comment]
#573

**Comment by jjqtony** [comment]
请求支持Reality协议，同请求，尽快纳入pre release中。

**Comment by MarksonHon** [comment]
@jjqtony Talking is cheap, show us your code.

**Comment by senkiss** [comment]
同求，reality比其它的相对稳和安全些
