### ISSUE TITLE
lan接口绑定为br-lan时，路由器重启进入恢复模式

### ISSUE THREAD

**Issue by zow2023** [daeuniverse/dae#607]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [ ] Is it your first time sumbitting an issue

### Current Behavior

路由器是linksysE8450， 用lienol大佬的默认分支编译的固件，内核是6.6.44。路由器作为主路由拨号，桥接光猫。下面连接了一个路由器做为AP。luci-app-daed用的是404大佬的源码，lan口绑定设置那里只要绑定为br-lan，提交后，点击打开按钮。路由器就会自动重启进入恢复模式
另外本人是菜鸟 还望大家赐教。

### Steps to Reproduce

路由器是linksysE8450， 用lienol大佬的默认分支编译的固件，内核是6.6.44。路由器作为主路由拨号，桥接光猫。下面连接了一个路由器做为AP。luci-app-daed用的是404大佬的源码，lan口绑定设置那里只要绑定为br-lan，提交后，点击打开按钮。路由器就会自动重启进入恢复模式

### Environment

- PKG_NAME:=daed
PKG_VERSION:=991f627
DAED_VERSION:=daed-991f627
CORE_VERSION:=core-817e448
openwrt-master(lienol-master)
kernel-6.6.44

**Comment by MarksonHon** [comment]
非软件本身故障，可以进群聊：
https://t.me/daeuniverse

**Comment by AkinoKaede** [comment]
I had a similar issue, try turning off GRO using this patch, which fixed the issue on my device.

https://github.com/coolsnowwolf/lede/commit/deb218ea2e7fc8ec163cea496286ef2145cc9e34

In addition, you can also sync to latest openwrt mainline, it contains a fix for GSO.

https://github.com/openwrt/openwrt/commit/17f07040e7808a0c9cba2afc0e0b22e5589da133

**Comment by zow2023** [comment]
> I had a similar issue, try turning off GRO using this patch, which fixed the issue on my device.
> 
> [coolsnowwolf/lede@deb218e](https://github.com/coolsnowwolf/lede/commit/deb218ea2e7fc8ec163cea496286ef2145cc9e34)
> 
> In addition, you can also sync to latest openwrt mainline, it contains a fix for GSO.
> 
> [openwrt/openwrt@17f0704](https://github.com/openwrt/openwrt/commit/17f07040e7808a0c9cba2afc0e0b22e5589da133)

感谢你的指导

**Comment by zow2023** [comment]
> I had a similar issue, try turning off GRO using this patch, which fixed the issue on my device.
> 
> [coolsnowwolf/lede@deb218e](https://github.com/coolsnowwolf/lede/commit/deb218ea2e7fc8ec163cea496286ef2145cc9e34)
> 
> In addition, you can also sync to latest openwrt mainline, it contains a fix for GSO.
> 
> [openwrt/openwrt@17f0704](https://github.com/openwrt/openwrt/commit/17f07040e7808a0c9cba2afc0e0b22e5589da133)

我今天拉取最新的官方源码 编译 还是一样的情况啊  大鹅看样子是吃不上了。，。

**Comment by zow2023** [comment]
> > > I had a similar issue, try turning off GRO using this patch, which fixed the issue on my device.
> > > [coolsnowwolf/lede@deb218e](https://github.com/coolsnowwolf/lede/commit/deb218ea2e7fc8ec163cea496286ef2145cc9e34)
> > > In addition, you can also sync to latest openwrt mainline, it contains a fix for GSO.
> > > [openwrt/openwrt@17f0704](https://github.com/openwrt/openwrt/commit/17f07040e7808a0c9cba2afc0e0b22e5589da133)
> > 
> > 
> > 我今天拉取最新的官方源码 编译 还是一样的情况啊 大鹅看样子是吃不上了。，。
> 
> Try to disable GRO like [coolsnowwolf/lede@deb218e](https://github.com/coolsnowwolf/lede/commit/deb218e), I don't guarantee this will work.

感谢你的指教  第二个办法 删掉6.6下的那两个文件  可以了  我已经运行30多分钟了，，。
