### ISSUE TITLE
[Support Request] Reality协议无法使用

### ISSUE THREAD

**Issue by gafans** [daeuniverse/dae#611]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

希望重新测试Reality协议,这是目前相对稳定的协议

### Current Behavior

https://github.com/daeuniverse/dae/pull/573 我看了一些帖子发现有人可以实现,但是我又按照他的配置测试,发现完全不行
,我使用其他协议节点是可以正常返回的,但是Reality就不行
curl https://www.google.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 

### Steps to Reproduce

us: 'vless://xxx@a.b.c:443?security=reality&type=tcp&flow=xtls-rprx-vision&pbk=zzz&sni=example.com&fp=chrome'

### Environment

- **Dae version (use `dae --version`)**:v0.7.1
- **OS (e.g `cat /etc/os-release`)**:Ubuntu 24.04 LTS
- **Kernel (e.g. `uname -a`)**: 6.9.11-1-liquorix-amd64
- **Others**:

**Comment by Mitsuhaxy** [comment]
貌似还没有合并吧

**Comment by MarksonHon** [comment]
去PR下反馈，别开新issue
