### ISSUE TITLE
[Enhancement] 对每个group支持配置单独的节点连通性检查策略

### ISSUE THREAD

**Issue by KagurazakaNyaa** [daeuniverse/dae#619]
### Improvement Suggestion

目前节点连通性检查只有`global`配置里的`tcp_check_url`,`tcp_check_http_method`,`udp_check_dns`,`check_interval`和`check_tolerance`
但是如果使用不同的`group`的一个常见场景是对于不同的目标使用不同的代理去访问，比如有的代理延迟低，有的代理带宽高，有的代理流量便宜但是限制端口之类的，这时候就需要针对不同的目标配置不同的连通性检查，然后通过写`routing`来路由到正确的`group`上

建议的两种解决方案：
- 把上述`global`配置中的字段认为是默认值，允许在`group`配置中覆盖对于此`group`的节点连通性检查配置
- 把连通性检查拆分成单独的`check`段，在`group`的`filter`中添加`pass_check(check1)`这种过滤器来引用连通性检查，原先`global`中的配置作为每个`filter`的默认引用或直接无效

### Potential Benefits

增强配置的灵活性，适配更多使用场景

**Comment by mzz2017** [comment]
> 比如有的代理延迟低，有的代理带宽高，有的代理流量便宜但是限制端口之类的

怎么通过联通性检测来选出相应的节点呢？

**Comment by st0nie** [comment]
这个需求可以用add_latency来解决
#119

**Comment by KagurazakaNyaa** [comment]
> > 比如有的代理延迟低，有的代理带宽高，有的代理流量便宜但是限制端口之类的
> 
> 怎么通过联通性检测来选出相应的节点呢？

不能直接通过联通性检测选取，但是可以通过联通性检测排除连接不到特定站点的节点，比如有的代理只能访问80和443端口，对于那种高位端口就访问不到，所以不可用于类似于`europe.vrdesktop.net:31194`这种对端的代理
而且不同的group因为不同的路由规则，适合使用的检测也不一样，比如用于很多游戏的代理适合使用`http://test.steampowered.com`，但是对于日常访问网页就适合用`https://cp.cloudflare.com`或者`https://www.google.com/genreate_204`这种作为联通性检测



> 这个需求可以用add_latency来解决 #119

不能，有的节点只能访问特定的端口或者部分对端无法访问，add_latency无法处理这种情况，不能假设所有的节点都可以访问所有的服务

**Comment by mzz2017** [comment]
这意味着每个节点可能会有多个节点连通性检测 url，这可能对于 dae 目前本来就有 tcp/udp/tcpdns/udpdns 来说是个负担，多一个就会 +4

**Comment by KagurazakaNyaa** [comment]
> 这意味着每个节点可能会有多个节点连通性检测 url，这可能对于 dae 目前本来就有 tcp/udp/tcpdns/udpdns 来说是个负担，多一个 url 就会多 4*节点数

确实，我看了一下联通性检查的实现，似乎是直接写到dialer里作为dialer结构的一部分，意味着每多一个检查，在这个逻辑上就会多一倍的负担，也许我们有别的方式可以实现类似v2rayA里的outbound的延迟检测功能？
或者用我提到的第一种方案，允许group覆写这个配置，这样在filter过滤了以后就只有部分dialer需要被克隆和修改

**Comment by mzz2017** [comment]
@KagurazakaNyaa 是的，这部分group豁免全局的检测规则，形成单独的检测规则。听起来是个可以接受的方案。
我预感到这部分的代码变动将会比较大，如果你有兴趣可以试着做一版出来。

**Comment by KagurazakaNyaa** [comment]
> @KagurazakaNyaa 是的，这部分group豁免全局的检测规则，形成单独的检测规则。尽可能减少未用到的节点的检测，听起来是个可以接受的方案。 我预感到这部分的代码变动将会比较大，如果你有兴趣可以试着做一版出来。

行，我这几天试试改一个出来

**Comment by KagurazakaNyaa** [comment]
@mzz2017 试着改了一版出来，测试了一下好像负载没有显著增加，应该是因为已经被filter过滤过所以节点数量不算多，可能需要进一步测试
