### ISSUE TITLE
[Feature Request] Supports SplitHTTP

### ISSUE THREAD

**Issue by luanyaolingwu** [daeuniverse/dae#622]
### Feature Request

Supports SplitHTTP

### Use Cases

My server uses the SplitHTTP protocol, and I'd like to be able to use it on daed.

### Potential Benefits

My server is using the SplitHTTP protocol.

**Comment by MarksonHon** [comment]
It won't be supported yet for none of document provided.

**Comment by luanyaolingwu** [comment]
SplitHTTP is now XHTTP. It has been officially released in XRay version 1.8.24+. For more information, visit:
 - [XHTTP ALSO SplitHTTP Transport Protocol](https://github.com/XTLS/Xray-core/tree/main/transport/internet/splithttp) 
 - [XRay Config Reference](https://xtls.github.io/config/transports/splithttp.html)

I really hope that dae will support this transport protocol. Thank you!
