### ISSUE TITLE
[ENHANCE] Config checker not working on reload

### ISSUE THREAD

**Issue by yqlbu** [daeuniverse/dae#66]
## What would you like us to improve

Currently, I am using dae with version `v0.1.7`. I noticed that when doing `dae reload`, it does NOT check the config syntax even though there is an error.

## Why is this needed

This should be considered a minor issue. However, if the functionality of checking syntax errors can be inherited to `reload`, that would certainly bring additional joy when using dae.

**Comment by mzz2017** [comment]
Not really. dae will check the config and rollback if new config is bad. Please check your log. It is likely overwheeled by other logs.
