### ISSUE TITLE
[Enhancement] about bandwidth usage units

### ISSUE THREAD

**Issue by douglarek** [daeuniverse/dae#665]
### Improvement Suggestion

The bandwidth recommended configuration settings of dae's hy2 uses the IEC standard:

```
# The maximum bandwidth for accessing the Internet. It is useful for some specific protocols (e.g., Hysteria2), 
# which will perform better with bandwith information provided. The unit is **byte** per second.
bandwidth_max_tx: 26214400 # 200Mbps == 25MB/s == 26214400 B/s uplink
bandwidth_max_rx: 131072000 # 1Gbps == 125MB/s == 131072000 B/s downlink
```

In theory, it seems that the SI standard should be used instead of the IEC standard. If DAE unilaterally uses IEC, issues may arise when using other servers (although they might be minor).

* https://www.pshinecable.com/article/is-1gbps-equal-to-1000mbps-or-1024mbps.html (prefer SI)
* https://v2.hysteria.network/zh/docs/advanced/Full-Client-Config/#_5 (prefer SI)
* https://sing-box.sagernet.org/configuration/inbound/hysteria2/#up_mbps-down_mbps (prefer SI)
* https://wiki.metacubex.one/config/proxies/hysteria2/#updown (prefer SI)

any thoughts here? @mnixry @mz

### Potential Benefits

Consistent with other implementations (including the original hy2 implementation)

**Comment by mnixry** [comment]
You are right; SI units is correct.

By the way, there's a TODO that needs to be addressed:

https://github.com/daeuniverse/dae/blob/2a8b5375ae593022c4a8bab46d585d36fddef9a1/config/config.go#L46-L48

Can you resolve the configuration example issue and implement this task? You can refer to the following section to adopt a usable configuration:

https://github.com/apernet/hysteria/blob/master/app/internal/utils/bpsconv.go#L59
