### ISSUE TITLE
如何正确配置全局模式？

### ISSUE THREAD

**Issue by qazwsdc** [daeuniverse/dae#684]
dns设置为
upstream {
  googledns: 'tcp+udp://8.8.8.8:53'
}
路由为
pname(NetworkManager, systemd-resolved, dnsmasq) -> must_direct
dip(geoip:private) -> direct
fallback: proxy

这样设置后，少部分连接仍然走国内。在dae日志中看不到任何直连流量，非常蹊跷

**Comment by qazwsdc** [comment]
dns默认的asis，还会走谷歌dns吗

**Comment by mzz2017** [comment]
@qazwsdc 不会

**Comment by qazwsdc** [comment]
upstream {
  googledns: 'tcp+udp://8.8.8.8:53'
}
routing {
  request {
    fallback: googledns
  }
}

这样配置全局吗？

**Comment by xinyifly** [comment]
@qazwsdc 

```
dns {
  routing {
    request { fallback: googledns }
  }
  upstream {
    googledns: 'tcp+udp://8.8.8.8:53'
  }
}

routing {
  pname(NetworkManager, systemd-resolved, dnsmasq) -> must_direct
  dip(geoip:private) -> direct
  fallback: proxy
}
```

dns 和 routing 分开配置
