### ISSUE TITLE
optimize: cache NXDomain and reject with 0.0.0.0 may caused issue

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#69]
## What happened:
ifeng.com slow to open, the problem disappears after rolling back to the file before this change. 

## Environment:

- Dae version (use `dae --version`):
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mzz2017** [comment]
Hard to reproduce. Please paste your config.

**Comment by BOBINIUNIU** [comment]
Cleared the dns cache problem was solved, maybe it was a problem with adguardhome. Thank you and have a nice vacation.
