### ISSUE TITLE
[Bug Report] dependency 'github.com/panjf2000/ants v1.3.0' missing 

### ISSUE THREAD

**Issue by cospotato** [daeuniverse/dae#701]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

```
# go mod download
go: github.com/panjf2000/ants@v1.3.0: reading github.com/panjf2000/ants/go.mod at revision v1.3.0: unknown revision v1.3.0
```

### Expected Behavior

build success

### Steps to Reproduce

1. clear go mod cache
2. git clone this project
3. run `go mod download`

### Environment

- **Dae version (use `dae --version`)**: `main`
- **OS (e.g `cat /etc/os-release`)**: 
```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
- **Kernel (e.g. `uname -a`)**: `Linux dev 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:
```
# go version
go version go1.22.4 linux/amd64
```

### Anything else?

The `github.com/panjf2000/ants v1.3.0` was introduced by #645

**Comment by mzz2017** [comment]
可否帮忙 pr 修复一下？
