### ISSUE TITLE
[Support Request] DAED 报 failed to GetOrCreate: protocol does not support udp

### ISSUE THREAD

**Issue by davidtall** [daeuniverse/dae#711]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

导入vlesss 协议  vless://xxx@xxx.com:20729?encryption=none&security=tls&fp=chrome&type=tcp&host=xxx.com&headerType=none&sni=xxx.com&flow=xtls-rprx-vision#davidtall-VLESS_TCP/TLS_Vision
能正常使用，但是日志回打印多条
```
time="Dec 05 23:54:50" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
time="Dec 05 23:54:51" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
time="Dec 05 23:54:52" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
time="Dec 05 23:54:53" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
time="Dec 05 23:54:54" level=warning msg="handlePkt: failed to GetOrCreate: protocol does not support udp"
```

路由设置如下
```
pname(NetworkManager, systemd-resolved, dnsmasq) -> must_direct
dip(geoip:private) -> direct
l4proto(udp) && !dport(53, 443) -> direct
#domain(geosite:geolocation-!cn) -> proxy

domain(suffix:cloudfront.net) -> direct
domain(suffix:chippay.com) -> direct
domain(suffix:tradingview.com) -> proxy
domain(geosite:onedrive) -> direct
dip(geoip:cn) -> direct
domain(geosite:cn) -> direct
fallback: proxy
```
DNS 
```
upstream {
  alidns: 'udp://223.5.5.5:53'
  googledns: 'tcp+udp://8.8.8.8:53'
}
routing {
  request {
    qname(geosite:cn) -> alidns
    fallback: googledns
  }
}
```
请问这个个警告是什么原因导致的呢？

### Current Behavior

无

### Steps to Reproduce

无

### Environment

dae 版本 https://github.com/daeuniverse/dae/commit/1404f1a03b96b782186ffe74ff9dd3260188ce07
daed 版本 0.8.0
使用luci 源码编译 https://github.com/QiuSimons/luci-app-daed

内核版本6.6.63

**Comment by cubatic45** [comment]
可以测试直接使用 https://github.com/QiuSimons/luci-app-daed 编译好的试一下

**Comment by davidtall** [comment]
> 可以直接使用 https://github.com/QiuSimons/luci-app-daed 编译好的试一下

使用了，一样会出现这样的日志，跟 https://github.com/daeuniverse/dae/issues/571#issuecomment-2466167452 这里写的一样，这个意思是这个vless 协议不支持UDP吗？能正常代理使用，只是好奇为什么会报这样的日志

**Comment by cubatic45** [comment]
> > 可以直接使用 https://github.com/QiuSimons/luci-app-daed 编译好的试一下
> 
> 使用了，一样会出现这样的日志，跟 [#571 (comment)](https://github.com/daeuniverse/dae/issues/571#issuecomment-2466167452) 这里写的一样，这个意思是这个vless 协议不支持UDP吗？能正常代理使用，只是好奇为什么会报这样的日志

daed-b44c472_wing-c4c7159_core-1404f1a 这个版本的 daed 测试 udp 是没有问题的
