### ISSUE TITLE
[Bug Report] <title>无法设置 DAE 网络： IpRouteAdd： 文件存在

### ISSUE THREAD

**Issue by GWU00099** [daeuniverse/dae#718]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

time="Dec 21 17:35:56" level=info msg="Include config files: [/etc/dae/config.dae]"
time="Dec 21 17:35:56" level=info msg="Waiting for network..."
time="Dec 21 17:35:56" level=info msg="Network online."
time="Dec 21 17:35:56" level=info msg="Fetching subscriptions..."
time="Dec 21 17:35:58" level=fatal msg="failed to setup dae netns: IpRouteAdd: file exists"
~
"/var/log/dae.log" [readonly] 5L, 361B 

### Expected Behavior

dae run -c /etc/dae/config.dae
[Dec 21 17:36:10]  INFO Include config files: [/etc/dae/config.dae]
[Dec 21 17:36:10]  INFO Waiting for network...
[Dec 21 17:36:10]  INFO Network online.
[Dec 21 17:36:10]  INFO Fetching subscriptions...
[Dec 21 17:36:12] FATAL failed to setup dae netns: IpRouteAdd: file exists

### Steps to Reproduce

```
global {
  # 绑定到 LAN 和/或 WAN 接口。将下述接口替换成你自己的接口名。
  #lan_interface: docker0
  wan_interface: auto # 使用 "auto" 自动侦测 WAN 接口。

  log_level: info
  allow_insecure: false
  auto_config_kernel_parameter: true
}

subscription {
  # 在下面填入你的订阅链接。
'https://不可以看哦'
}

# 更多的 DNS 样例见 https://github.com/daeuniverse/dae/blob/main/docs/en/configuration/dns.md
dns {
  upstream {
    googledns: 'tcp+udp://dns.google:53'
    alidns: 'udp://dns.alidns.com:53'
  }
  routing {
    request {
      qtype(https) -> reject
      fallback: alidns
    }
    response {
      upstream(googledns) -> accept
      ip(geoip:private) && !qname(geosite:cn) -> googledns
      fallback: accept
    }
  }
}

group {
  proxy {
    #filter: name(keyword: HK, keyword: SG)
    policy: min_moving_avg
  }
}

# 更多的 Routing 样例见 https://github.com/daeuniverse/dae/blob/main/docs/en/configuration/routing.md
routing {
  pname(NetworkManager) -> direct
  dip(224.0.0.0/3, 'ff00::/8') -> direct

  ### 以下为自定义规则

  # 禁用 h3，因为它通常消耗很多 CPU 和内存资源
  l4proto(udp) && dport(443) -> block
  dip(geoip:private) -> direct
  dip(geoip:cn) -> direct
  domain(geosite:cn) -> direct

  fallback: proxy
}

```
### Environment

OS: Gentoo Linux x86_64
init: OpenRC #  OpenRC已经根据 https://github.com/daeuniverse/dae-installer 配置
dae-0.9.0

**Comment by MarksonHon** [comment]
@GWU00099 那你init怎么写的，cgroup与btf挂载了没有

**Comment by MarksonHon** [comment]
No reply, closed.

**Comment by GWU00099** [comment]
@MarksonHon 问题已经决绝我需要删除这个issue
