### ISSUE TITLE
[Support Request] DNS Cache problem

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#83]
## What happened:
Does dae have DNS cache? I have DDNS configured on my router and nslookup can return the correct IP if not connected through dae. If connected via dae it always returns the old IP unless I restart the dae service
## Environment:

- Dae version (use `dae --version`):
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mzz2017** [comment]
@BOBINIUNIU Yes. dae has cache. You expect to bypass cache for some domains?

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU Yes. dae has cache. You expect to bypass cache for some domains?
No, we don't need new feature. The problem is the cached results cannot be updated.
The TTL for my domain is 10 minutes, however, the nslookup command query is still returning cached results after few hours. dae should update the cached result after the TTL expires.

**Comment by BOBINIUNIU** [comment]
Could you please add a switch to disable dae dns cache? Users who use external dns services may encounter some problems.

**Comment by mzz2017** [comment]
@BOBINIUNIU DNS cache should update after ttl. I'll check it.

**Comment by BOBINIUNIU** [comment]
I think a dns cache switch is the best solution. This would avoid the problems caused by multiple dns caches.

**Comment by MarksonHon** [comment]
你可以说中文的
Actually you can speak Chinese here

**Comment by yqlbu** [comment]
@MarksonHon 🌚🌚🌚

**Comment by BOBINIUNIU** [comment]
> 你可以说中文的 Actually you can speak Chinese here

Actually we all can speak Chinese here, only the people in the WALL use this software. 哈哈
