### ISSUE TITLE
DNS缓存建议

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#91]
## What would you like us to support (In short summary)

为了避免系统中存在多个DNS缓存，对于同时使用dae和其他DNS服务程序 （如dnsmasq，coredns，adguardhome）的用户，是否应该建议将DNS服务程序的缓存disable?

**Comment by mzz2017** [comment]
@BOBINIUNIU 如果你的adguardhome在dae下游，建议disable，在上游则无所谓

**Comment by BOBINIUNIU** [comment]
已经将adguardhome的缓存disable，最新的版本已经修复了所有问题，谢谢。
如果能增加缓存开关，最大最小TTL和缓存大小的设置就完美了。
