### ISSUE TITLE
DNS缓存仍然有些问题

### ISSUE THREAD

**Issue by BOBINIUNIU** [daeuniverse/dae#96]
## What happened:
我注意到dae的DNS缓存更新比较慢，上游DNS的查询结果已经更新，但是dae的缓存却迟迟不更新。
请考虑设计禁用DNS缓存的功能。目前的操作系统和路由器都自带了DNS缓存功能，网关有没有缓存应该是无所谓的。
如果您觉得缓存是有必要的，请让用户自行设置缓存时间或者选择哪些域名不缓存。
非常感谢你带来如此强大而简洁的程序，祝周末愉快 ；）

## Environment:

- Dae version (use `dae --version`):
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mzz2017** [comment]
@BOBINIUNIU 1. 对你有什么影响？
2. 什么拓扑需要dae请求一个有缓存且不给正确ttl的上游dns？
3. 操作系统如linux默认是不缓存的。

**Comment by mzz2017** [comment]
@BOBINIUNIU 另外请帮忙确认一下较早版本如0.1.1是否存在问题，那时候没有最低缓存2分钟的限制，谢谢

**Comment by BOBINIUNIU** [comment]
1. 绝大多数网站是没有问题的，有问题的是DDNS，因为IP经常改变。直连IP已经更新了，但是通过dae仍然返回过期的IP
2. 我的环境是Debian 安装dae和Core DNS，Core DNS的缓存已经关闭。
3. 晚点我确认一下0.1.1版看看问题是否存在。我记得刚刚使用dae的时候没有这个问题。

**Comment by mzz2017** [comment]
@BOBINIUNIU 好的，可以修改可以revert，如果老版本也有问题，可以考虑加个nocache选项

**Comment by BOBINIUNIU** [comment]
0.1.1在我的配置下无法启动，我测试了v0.1.3，这个问题仍然存在。

**Comment by mzz2017** [comment]
https://github.com/daeuniverse/dae/pull/100
https://github.com/daeuniverse/dae/actions/runs/5097294948

尝试添加新的选项 fixed_domain_ttl 来修复此问题

**Comment by BOBINIUNIU** [comment]
> #100 https://github.com/daeuniverse/dae/actions/runs/5097294948
> 
> 尝试添加新的选项 fixed_domain_ttl 来修复此问题

感谢修复！测试后反馈。

**Comment by BOBINIUNIU** [comment]
fixed_domain_ttl worked! 
P.S 这个参数支持通配符吗？例如 *.abc.com 匹配所有abc.com的子域名， * 匹配所有域名。

**Comment by mzz2017** [comment]
@BOBINIUNIU 我觉得不支持也行吧

**Comment by BOBINIUNIU** [comment]
> @BOBINIUNIU 我觉得不支持也行吧

嗯，已经够用了
